# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created: Tue May  7 13:54:15 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(953, 678)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.function_menu = QtGui.QWidget(self.centralwidget)
        self.function_menu.setObjectName(_fromUtf8("function_menu"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.function_menu)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btn_choose_files = QtGui.QToolButton(self.function_menu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/choose_files.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_choose_files.setIcon(icon)
        self.btn_choose_files.setIconSize(QtCore.QSize(64, 64))
        self.btn_choose_files.setCheckable(True)
        self.btn_choose_files.setChecked(True)
        self.btn_choose_files.setAutoExclusive(True)
        self.btn_choose_files.setAutoRaise(True)
        self.btn_choose_files.setObjectName(_fromUtf8("btn_choose_files"))
        self.horizontalLayout.addWidget(self.btn_choose_files)
        self.btn_step1 = QtGui.QToolButton(self.function_menu)
        self.btn_step1.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/right-arrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_step1.setIcon(icon1)
        self.btn_step1.setIconSize(QtCore.QSize(32, 32))
        self.btn_step1.setCheckable(False)
        self.btn_step1.setAutoRaise(True)
        self.btn_step1.setObjectName(_fromUtf8("btn_step1"))
        self.horizontalLayout.addWidget(self.btn_step1)
        self.btn_analyze = QtGui.QToolButton(self.function_menu)
        self.btn_analyze.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/analyze.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_analyze.setIcon(icon2)
        self.btn_analyze.setIconSize(QtCore.QSize(64, 64))
        self.btn_analyze.setCheckable(True)
        self.btn_analyze.setChecked(False)
        self.btn_analyze.setAutoExclusive(True)
        self.btn_analyze.setAutoRaise(True)
        self.btn_analyze.setObjectName(_fromUtf8("btn_analyze"))
        self.horizontalLayout.addWidget(self.btn_analyze)
        self.btn_step2 = QtGui.QToolButton(self.function_menu)
        self.btn_step2.setEnabled(False)
        self.btn_step2.setIcon(icon1)
        self.btn_step2.setIconSize(QtCore.QSize(32, 32))
        self.btn_step2.setCheckable(False)
        self.btn_step2.setAutoRaise(True)
        self.btn_step2.setObjectName(_fromUtf8("btn_step2"))
        self.horizontalLayout.addWidget(self.btn_step2)
        self.btn_experiment = QtGui.QToolButton(self.function_menu)
        self.btn_experiment.setEnabled(False)
        self.btn_experiment.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/show_results.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_experiment.setIcon(icon3)
        self.btn_experiment.setIconSize(QtCore.QSize(64, 64))
        self.btn_experiment.setCheckable(True)
        self.btn_experiment.setAutoExclusive(True)
        self.btn_experiment.setAutoRaise(True)
        self.btn_experiment.setObjectName(_fromUtf8("btn_experiment"))
        self.horizontalLayout.addWidget(self.btn_experiment)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_about = QtGui.QToolButton(self.function_menu)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/help-about.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_about.setIcon(icon4)
        self.btn_about.setIconSize(QtCore.QSize(64, 64))
        self.btn_about.setCheckable(True)
        self.btn_about.setAutoExclusive(True)
        self.btn_about.setAutoRaise(True)
        self.btn_about.setObjectName(_fromUtf8("btn_about"))
        self.horizontalLayout.addWidget(self.btn_about)
        self.verticalLayout.addWidget(self.function_menu)
        self.main_screen = QtGui.QStackedWidget(self.centralwidget)
        self.main_screen.setObjectName(_fromUtf8("main_screen"))
        self.page_choose = QtGui.QWidget()
        self.page_choose.setObjectName(_fromUtf8("page_choose"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page_choose)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.grp_choose_files = QtGui.QGroupBox(self.page_choose)
        self.grp_choose_files.setObjectName(_fromUtf8("grp_choose_files"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.grp_choose_files)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.widget_3 = QtGui.QWidget(self.grp_choose_files)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.widget_4 = QtGui.QWidget(self.widget_3)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.widget_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.btn_dir_add = QtGui.QPushButton(self.widget_4)
        self.btn_dir_add.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/add-dir.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_dir_add.setIcon(icon5)
        self.btn_dir_add.setIconSize(QtCore.QSize(32, 32))
        self.btn_dir_add.setFlat(True)
        self.btn_dir_add.setObjectName(_fromUtf8("btn_dir_add"))
        self.horizontalLayout_4.addWidget(self.btn_dir_add)
        self.btn_file_add = QtGui.QPushButton(self.widget_4)
        self.btn_file_add.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/add-file.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_file_add.setIcon(icon6)
        self.btn_file_add.setIconSize(QtCore.QSize(32, 32))
        self.btn_file_add.setFlat(True)
        self.btn_file_add.setObjectName(_fromUtf8("btn_file_add"))
        self.horizontalLayout_4.addWidget(self.btn_file_add)
        self.btn_file_remove = QtGui.QPushButton(self.widget_4)
        self.btn_file_remove.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/list-remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_file_remove.setIcon(icon7)
        self.btn_file_remove.setIconSize(QtCore.QSize(32, 32))
        self.btn_file_remove.setFlat(True)
        self.btn_file_remove.setObjectName(_fromUtf8("btn_file_remove"))
        self.horizontalLayout_4.addWidget(self.btn_file_remove)
        self.verticalLayout_7.addWidget(self.widget_4)
        self.gui_file_list = QtGui.QListView(self.widget_3)
        self.gui_file_list.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.gui_file_list.setObjectName(_fromUtf8("gui_file_list"))
        self.verticalLayout_7.addWidget(self.gui_file_list)
        self.widget_5 = QtGui.QWidget(self.widget_3)
        self.widget_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_7.addWidget(self.widget_5)
        self.horizontalLayout_3.addWidget(self.widget_3)
        self.verticalLayout_2.addWidget(self.grp_choose_files)
        self.main_screen.addWidget(self.page_choose)
        self.page_analyze = QtGui.QWidget()
        self.page_analyze.setObjectName(_fromUtf8("page_analyze"))
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.page_analyze)
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.groupBox = QtGui.QGroupBox(self.page_analyze)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 4, 4, 1, 1)
        self.lbl_select_piece = QtGui.QLabel(self.groupBox)
        self.lbl_select_piece.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_select_piece.setObjectName(_fromUtf8("lbl_select_piece"))
        self.gridLayout_2.addWidget(self.lbl_select_piece, 3, 4, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 2, 4, 1, 1)
        self.widget_6 = QtGui.QWidget(self.groupBox)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gridLayout_2.addWidget(self.widget_6, 0, 4, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 1, 1, 1)
        self.grp_settings_for_piece = QtGui.QGroupBox(self.groupBox)
        self.grp_settings_for_piece.setObjectName(_fromUtf8("grp_settings_for_piece"))
        self.gridLayout_3 = QtGui.QGridLayout(self.grp_settings_for_piece)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 3, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem6, 6, 1, 1, 1)
        self.btn_add_check_combo = QtGui.QPushButton(self.grp_settings_for_piece)
        self.btn_add_check_combo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add_check_combo.sizePolicy().hasHeightForWidth())
        self.btn_add_check_combo.setSizePolicy(sizePolicy)
        self.btn_add_check_combo.setObjectName(_fromUtf8("btn_add_check_combo"))
        self.gridLayout_3.addWidget(self.btn_add_check_combo, 9, 0, 1, 1)
        self.line_offset_interval = QtGui.QLineEdit(self.grp_settings_for_piece)
        self.line_offset_interval.setEnabled(False)
        self.line_offset_interval.setInputMask(_fromUtf8(""))
        self.line_offset_interval.setMaxLength(256)
        self.line_offset_interval.setObjectName(_fromUtf8("line_offset_interval"))
        self.gridLayout_3.addWidget(self.line_offset_interval, 0, 1, 1, 1)
        self.lbl_offset_interval = QtGui.QLabel(self.grp_settings_for_piece)
        self.lbl_offset_interval.setObjectName(_fromUtf8("lbl_offset_interval"))
        self.gridLayout_3.addWidget(self.lbl_offset_interval, 0, 0, 1, 1)
        self.line_compare_these_parts = QtGui.QLineEdit(self.grp_settings_for_piece)
        self.line_compare_these_parts.setEnabled(False)
        self.line_compare_these_parts.setInputMask(_fromUtf8(""))
        self.line_compare_these_parts.setObjectName(_fromUtf8("line_compare_these_parts"))
        self.gridLayout_3.addWidget(self.line_compare_these_parts, 7, 1, 1, 2)
        self.lbl_compare_these_parts = QtGui.QLabel(self.grp_settings_for_piece)
        self.lbl_compare_these_parts.setObjectName(_fromUtf8("lbl_compare_these_parts"))
        self.gridLayout_3.addWidget(self.lbl_compare_these_parts, 7, 0, 1, 1)
        self.btn_choose_note = QtGui.QPushButton(self.grp_settings_for_piece)
        self.btn_choose_note.setEnabled(False)
        self.btn_choose_note.setObjectName(_fromUtf8("btn_choose_note"))
        self.gridLayout_3.addWidget(self.btn_choose_note, 0, 2, 1, 1)
        self.widget_2 = QtGui.QWidget(self.grp_settings_for_piece)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.widget_part_boxes = QtGui.QWidget(self.widget_2)
        self.widget_part_boxes.setObjectName(_fromUtf8("widget_part_boxes"))
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.widget_part_boxes)
        self.verticalLayout_22.setMargin(0)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.chk_all_voice_combos = QtGui.QCheckBox(self.widget_part_boxes)
        self.chk_all_voice_combos.setEnabled(False)
        self.chk_all_voice_combos.setObjectName(_fromUtf8("chk_all_voice_combos"))
        self.verticalLayout_22.addWidget(self.chk_all_voice_combos)
        self.horizontalLayout_9.addWidget(self.widget_part_boxes)
        self.gridLayout_3.addWidget(self.widget_2, 8, 0, 1, 3)
        self.line_piece_title = QtGui.QLineEdit(self.grp_settings_for_piece)
        self.line_piece_title.setObjectName(_fromUtf8("line_piece_title"))
        self.gridLayout_3.addWidget(self.line_piece_title, 5, 1, 1, 2)
        self.lbl_piece_title = QtGui.QLabel(self.grp_settings_for_piece)
        self.lbl_piece_title.setObjectName(_fromUtf8("lbl_piece_title"))
        self.gridLayout_3.addWidget(self.lbl_piece_title, 5, 0, 1, 1)
        self.chk_repeat_identical = QtGui.QCheckBox(self.grp_settings_for_piece)
        self.chk_repeat_identical.setObjectName(_fromUtf8("chk_repeat_identical"))
        self.gridLayout_3.addWidget(self.chk_repeat_identical, 1, 0, 1, 3)
        self.gridLayout_2.addWidget(self.grp_settings_for_piece, 1, 4, 1, 1)
        self.gui_pieces_list = QtGui.QTableView(self.groupBox)
        self.gui_pieces_list.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.gui_pieces_list.setObjectName(_fromUtf8("gui_pieces_list"))
        self.gui_pieces_list.horizontalHeader().setMinimumSectionSize(2)
        self.gui_pieces_list.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.gui_pieces_list, 1, 0, 7, 3)
        self.verticalLayout_23.addWidget(self.groupBox)
        self.main_screen.addWidget(self.page_analyze)
        self.page_show = QtGui.QWidget()
        self.page_show.setObjectName(_fromUtf8("page_show"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page_show)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.page_show)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 4, 0, 1, 1)
        self.grp_octaves = QtGui.QGroupBox(self.groupBox_2)
        self.grp_octaves.setObjectName(_fromUtf8("grp_octaves"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.grp_octaves)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.rdo_compound = QtGui.QRadioButton(self.grp_octaves)
        self.rdo_compound.setChecked(True)
        self.rdo_compound.setObjectName(_fromUtf8("rdo_compound"))
        self.verticalLayout_13.addWidget(self.rdo_compound)
        self.rdo_simple = QtGui.QRadioButton(self.grp_octaves)
        self.rdo_simple.setObjectName(_fromUtf8("rdo_simple"))
        self.verticalLayout_13.addWidget(self.rdo_simple)
        self.gridLayout.addWidget(self.grp_octaves, 1, 0, 2, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.rdo_spreadsheet = QtGui.QRadioButton(self.groupBox_5)
        self.rdo_spreadsheet.setChecked(True)
        self.rdo_spreadsheet.setObjectName(_fromUtf8("rdo_spreadsheet"))
        self.verticalLayout_9.addWidget(self.rdo_spreadsheet)
        self.rdo_list = QtGui.QRadioButton(self.groupBox_5)
        self.rdo_list.setEnabled(False)
        self.rdo_list.setObjectName(_fromUtf8("rdo_list"))
        self.verticalLayout_9.addWidget(self.rdo_list)
        self.rdo_chart = QtGui.QRadioButton(self.groupBox_5)
        self.rdo_chart.setEnabled(False)
        self.rdo_chart.setChecked(False)
        self.rdo_chart.setObjectName(_fromUtf8("rdo_chart"))
        self.verticalLayout_9.addWidget(self.rdo_chart)
        self.gridLayout.addWidget(self.groupBox_5, 0, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 4, 1, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.rdo_consider_intervals = QtGui.QRadioButton(self.groupBox_7)
        self.rdo_consider_intervals.setEnabled(True)
        self.rdo_consider_intervals.setChecked(True)
        self.rdo_consider_intervals.setObjectName(_fromUtf8("rdo_consider_intervals"))
        self.verticalLayout_11.addWidget(self.rdo_consider_intervals)
        self.rdo_consider_interval_ngrams = QtGui.QRadioButton(self.groupBox_7)
        self.rdo_consider_interval_ngrams.setEnabled(True)
        self.rdo_consider_interval_ngrams.setChecked(False)
        self.rdo_consider_interval_ngrams.setObjectName(_fromUtf8("rdo_consider_interval_ngrams"))
        self.verticalLayout_11.addWidget(self.rdo_consider_interval_ngrams)
        self.rdo_consider_chord_ngrams = QtGui.QRadioButton(self.groupBox_7)
        self.rdo_consider_chord_ngrams.setEnabled(True)
        self.rdo_consider_chord_ngrams.setObjectName(_fromUtf8("rdo_consider_chord_ngrams"))
        self.verticalLayout_11.addWidget(self.rdo_consider_chord_ngrams)
        self.gridLayout.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.grp_quality = QtGui.QGroupBox(self.groupBox_2)
        self.grp_quality.setObjectName(_fromUtf8("grp_quality"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.grp_quality)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.rdo_heedQuality = QtGui.QRadioButton(self.grp_quality)
        self.rdo_heedQuality.setObjectName(_fromUtf8("rdo_heedQuality"))
        self.verticalLayout_10.addWidget(self.rdo_heedQuality)
        self.rdo_noHeedQuality = QtGui.QRadioButton(self.grp_quality)
        self.rdo_noHeedQuality.setChecked(True)
        self.rdo_noHeedQuality.setObjectName(_fromUtf8("rdo_noHeedQuality"))
        self.verticalLayout_10.addWidget(self.rdo_noHeedQuality)
        self.gridLayout.addWidget(self.grp_quality, 1, 1, 2, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 4, 2, 1, 1)
        self.grp_values_of_n = QtGui.QGroupBox(self.groupBox_2)
        self.grp_values_of_n.setObjectName(_fromUtf8("grp_values_of_n"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.grp_values_of_n)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.grp_values_of_n)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.line_values_of_n = QtGui.QLineEdit(self.grp_values_of_n)
        self.line_values_of_n.setObjectName(_fromUtf8("line_values_of_n"))
        self.verticalLayout_4.addWidget(self.line_values_of_n)
        self.gridLayout.addWidget(self.grp_values_of_n, 0, 2, 1, 1)
        self.btn_show_results = QtGui.QPushButton(self.groupBox_2)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/show_checkmark.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_show_results.setIcon(icon8)
        self.btn_show_results.setIconSize(QtCore.QSize(64, 64))
        self.btn_show_results.setObjectName(_fromUtf8("btn_show_results"))
        self.gridLayout.addWidget(self.btn_show_results, 4, 3, 1, 1)
        self.group_top_x = QtGui.QGroupBox(self.groupBox_2)
        self.group_top_x.setObjectName(_fromUtf8("group_top_x"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.group_top_x)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_2 = QtGui.QLabel(self.group_top_x)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_8.addWidget(self.label_2)
        self.line_top_x = QtGui.QLineEdit(self.group_top_x)
        self.line_top_x.setObjectName(_fromUtf8("line_top_x"))
        self.verticalLayout_8.addWidget(self.line_top_x)
        self.label_4 = QtGui.QLabel(self.group_top_x)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_8.addWidget(self.label_4)
        self.gridLayout.addWidget(self.group_top_x, 3, 0, 1, 1)
        self.group_threshold = QtGui.QGroupBox(self.groupBox_2)
        self.group_threshold.setObjectName(_fromUtf8("group_threshold"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.group_threshold)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_5 = QtGui.QLabel(self.group_threshold)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_12.addWidget(self.label_5)
        self.line_threshold = QtGui.QLineEdit(self.group_threshold)
        self.line_threshold.setObjectName(_fromUtf8("line_threshold"))
        self.verticalLayout_12.addWidget(self.line_threshold)
        self.gridLayout.addWidget(self.group_threshold, 3, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.main_screen.addWidget(self.page_show)
        self.page_working = QtGui.QWidget()
        self.page_working.setObjectName(_fromUtf8("page_working"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.page_working)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem11)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem12)
        self.btn_wait_clock = QtGui.QPushButton(self.page_working)
        self.btn_wait_clock.setEnabled(True)
        self.btn_wait_clock.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/working.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_wait_clock.setIcon(icon9)
        self.btn_wait_clock.setIconSize(QtCore.QSize(64, 64))
        self.btn_wait_clock.setCheckable(False)
        self.btn_wait_clock.setChecked(False)
        self.btn_wait_clock.setFlat(True)
        self.btn_wait_clock.setObjectName(_fromUtf8("btn_wait_clock"))
        self.horizontalLayout_8.addWidget(self.btn_wait_clock)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem13)
        self.verticalLayout_21.addLayout(self.horizontalLayout_8)
        self.lbl_status_text = QtGui.QLabel(self.page_working)
        self.lbl_status_text.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lbl_status_text.setObjectName(_fromUtf8("lbl_status_text"))
        self.verticalLayout_21.addWidget(self.lbl_status_text)
        self.progress_bar = QtGui.QProgressBar(self.page_working)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName(_fromUtf8("progress_bar"))
        self.verticalLayout_21.addWidget(self.progress_bar)
        self.lbl_currently_processing = QtGui.QLabel(self.page_working)
        self.lbl_currently_processing.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lbl_currently_processing.setObjectName(_fromUtf8("lbl_currently_processing"))
        self.verticalLayout_21.addWidget(self.lbl_currently_processing)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem14)
        self.btn_cancel_operation = QtGui.QPushButton(self.page_working)
        self.btn_cancel_operation.setObjectName(_fromUtf8("btn_cancel_operation"))
        self.verticalLayout_21.addWidget(self.btn_cancel_operation)
        self.main_screen.addWidget(self.page_working)
        self.page_about = QtGui.QWidget()
        self.page_about.setObjectName(_fromUtf8("page_about"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page_about)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_4 = QtGui.QGroupBox(self.page_about)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_copyright = QtGui.QLabel(self.groupBox_4)
        self.label_copyright.setObjectName(_fromUtf8("label_copyright"))
        self.verticalLayout_6.addWidget(self.label_copyright)
        self.line = QtGui.QFrame(self.groupBox_4)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_6.addWidget(self.line)
        self.label_about = QtGui.QLabel(self.groupBox_4)
        self.label_about.setObjectName(_fromUtf8("label_about"))
        self.verticalLayout_6.addWidget(self.label_about)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.main_screen.addWidget(self.page_about)
        self.verticalLayout.addWidget(self.main_screen)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.main_screen.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "vis", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_choose_files.setToolTip(QtGui.QApplication.translate("MainWindow", "Choose Files", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_step1.setToolTip(QtGui.QApplication.translate("MainWindow", "Continue to Step 2", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_analyze.setToolTip(QtGui.QApplication.translate("MainWindow", "Prepare and Assemble for Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_step2.setToolTip(QtGui.QApplication.translate("MainWindow", "Continue to the Step 3", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_experiment.setToolTip(QtGui.QApplication.translate("MainWindow", "Show and Save Results", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_about.setToolTip(QtGui.QApplication.translate("MainWindow", "About \"vis\"", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_choose_files.setTitle(QtGui.QApplication.translate("MainWindow", "Importer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Add files to the list so they will be imported.", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_dir_add.setToolTip(QtGui.QApplication.translate("MainWindow", "Add Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_file_add.setToolTip(QtGui.QApplication.translate("MainWindow", "Add Files", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_file_remove.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove Selected Items", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Analyzer", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_select_piece.setText(QtGui.QApplication.translate("MainWindow", "Select piece(s) to see possible settings.", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_settings_for_piece.setTitle(QtGui.QApplication.translate("MainWindow", "Settings for Selected Piece", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_add_check_combo.setText(QtGui.QApplication.translate("MainWindow", "Add Combination", None, QtGui.QApplication.UnicodeUTF8))
        self.line_offset_interval.setText(QtGui.QApplication.translate("MainWindow", "0.5", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_offset_interval.setText(QtGui.QApplication.translate("MainWindow", "Offset Interval:", None, QtGui.QApplication.UnicodeUTF8))
        self.line_compare_these_parts.setText(QtGui.QApplication.translate("MainWindow", "e.g., [0,3] or [[0,3],[1,3]]", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_compare_these_parts.setText(QtGui.QApplication.translate("MainWindow", "Compare These Parts:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_choose_note.setText(QtGui.QApplication.translate("MainWindow", "Choose Offset Note", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_all_voice_combos.setToolTip(QtGui.QApplication.translate("MainWindow", "Collect Statistics for all Part Combinations", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_all_voice_combos.setText(QtGui.QApplication.translate("MainWindow", "All Voice Pairs", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_piece_title.setText(QtGui.QApplication.translate("MainWindow", "Piece Title:", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_repeat_identical.setText(QtGui.QApplication.translate("MainWindow", "Repeat consecutive identical events", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Experimenter", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_octaves.setTitle(QtGui.QApplication.translate("MainWindow", "Octaves", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_compound.setText(QtGui.QApplication.translate("MainWindow", "Compound Intervals", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_simple.setText(QtGui.QApplication.translate("MainWindow", "Simple Intervals", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "How to Show Results", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_spreadsheet.setText(QtGui.QApplication.translate("MainWindow", "Spreadsheet", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_list.setText(QtGui.QApplication.translate("MainWindow", "List", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_chart.setText(QtGui.QApplication.translate("MainWindow", "Chart/Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Object to Consider", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_consider_intervals.setText(QtGui.QApplication.translate("MainWindow", "Intervals", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_consider_interval_ngrams.setText(QtGui.QApplication.translate("MainWindow", "Interval N-grams", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_consider_chord_ngrams.setText(QtGui.QApplication.translate("MainWindow", "Chord N-grams", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_quality.setTitle(QtGui.QApplication.translate("MainWindow", "Interval Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_heedQuality.setText(QtGui.QApplication.translate("MainWindow", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_noHeedQuality.setText(QtGui.QApplication.translate("MainWindow", "Ignore", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_values_of_n.setTitle(QtGui.QApplication.translate("MainWindow", "Values of N", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Please input values as a well-formatted<br/>list of python &quot;int&quot; objects, like this:<br/>[2]<br/>... or...<br/>[2, 3]</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_show_results.setText(QtGui.QApplication.translate("MainWindow", "Process and &Show", None, QtGui.QApplication.UnicodeUTF8))
        self.group_top_x.setTitle(QtGui.QApplication.translate("MainWindow", "\"Top X\" Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Show only the ...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "... highest results", None, QtGui.QApplication.UnicodeUTF8))
        self.group_threshold.setTitle(QtGui.QApplication.translate("MainWindow", "Threshold Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Do not show results<br/>with fewer than this<br/>many occurrences:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_wait_clock.setToolTip(QtGui.QApplication.translate("MainWindow", "Hi, mom!", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_status_text.setText(QtGui.QApplication.translate("MainWindow", "Please wait...", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_currently_processing.setText(QtGui.QApplication.translate("MainWindow", "(processing)", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_cancel_operation.setText(QtGui.QApplication.translate("MainWindow", "Cancel Operation", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Information about vis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_copyright.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" text-decoration: underline;\">vis 9 (Branched and Revised for the 11 May 2013 CIRMMT Workshop)</span></p><p>Copyright (c) 2012, 2013 Christopher Antila, Jamie Klassen, Alexander Morgan</p><p>This program is free software: you can redistribute it and/or modify<br/>it under the terms of the GNU General Public License as published by<br/>the Free Software Foundation, either version 3 of the License, or<br/>(at your option) any later version.</p><p>This program is distributed in the hope that it will be useful,<br/>but WITHOUT ANY WARRANTY; without even the implied warranty of<br/>MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the<br/>GNU General Public License for more details.</p><p>You should have received a copy of the GNU General Public License<br/>along with this program. If not, see &lt;http://www.gnu.org/licenses/&gt;.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_about.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>vis was written as part of McGill University\'s contribution to the ELVIS project.<br/>For more information about ELVIS, please refer to our <a href=\"http://elvis.music.mcgill.ca/\"><span style=\" text-decoration: underline; color:#0057ae;\">web site</span></a>.</p><p>Funding for ELVIS was provided by the following organizations:<br/>- SSHRC (Social Sciences and Humanities Research Council) of Canada<br/>- NEH (National Endowment for the Humanities) of the United States of America<br/>- The Digging into Data Challenge</p><p>vis is written in the Python programming language, and relies on the following<br/>software, all released under free licences:<br/>- <a href=\"http://mit.edu/music21/\"><span style=\" text-decoration: underline; color:#0057ae;\">music21<br/></span></a>- <a href=\"http://www.riverbankcomputing.co.uk/software/pyqt/download\"><span style=\" text-decoration: underline; color:#0057ae;\">PyQt4</span></a><br/>- <a href=\"http://www.oxygen-icons.org/\"><span style=\" text-decoration: underline; color:#0057ae;\">Oxygen Icons</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
