# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/crantila/Documents/ELVIS/programs/vis/gui_files/new_main_window.ui'
#
# Created: Mon Oct  1 21:54:57 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.function_menu = QtGui.QWidget(self.centralwidget)
        self.function_menu.setObjectName(_fromUtf8("function_menu"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.function_menu)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btn_choose_files = QtGui.QToolButton(self.function_menu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/choose_files.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_choose_files.setIcon(icon)
        self.btn_choose_files.setIconSize(QtCore.QSize(64, 64))
        self.btn_choose_files.setCheckable(True)
        self.btn_choose_files.setChecked(True)
        self.btn_choose_files.setAutoExclusive(True)
        self.btn_choose_files.setAutoRaise(True)
        self.btn_choose_files.setObjectName(_fromUtf8("btn_choose_files"))
        self.horizontalLayout.addWidget(self.btn_choose_files)
        self.btn_step1 = QtGui.QToolButton(self.function_menu)
        self.btn_step1.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/right-arrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_step1.setIcon(icon1)
        self.btn_step1.setIconSize(QtCore.QSize(32, 32))
        self.btn_step1.setAutoRaise(True)
        self.btn_step1.setObjectName(_fromUtf8("btn_step1"))
        self.horizontalLayout.addWidget(self.btn_step1)
        self.btn_analyze = QtGui.QToolButton(self.function_menu)
        self.btn_analyze.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/analyze.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_analyze.setIcon(icon2)
        self.btn_analyze.setIconSize(QtCore.QSize(64, 64))
        self.btn_analyze.setCheckable(True)
        self.btn_analyze.setChecked(False)
        self.btn_analyze.setAutoExclusive(True)
        self.btn_analyze.setAutoRaise(True)
        self.btn_analyze.setObjectName(_fromUtf8("btn_analyze"))
        self.horizontalLayout.addWidget(self.btn_analyze)
        self.btn_step2 = QtGui.QToolButton(self.function_menu)
        self.btn_step2.setEnabled(False)
        self.btn_step2.setIcon(icon1)
        self.btn_step2.setIconSize(QtCore.QSize(32, 32))
        self.btn_step2.setAutoRaise(True)
        self.btn_step2.setObjectName(_fromUtf8("btn_step2"))
        self.horizontalLayout.addWidget(self.btn_step2)
        self.btn_show = QtGui.QToolButton(self.function_menu)
        self.btn_show.setEnabled(False)
        self.btn_show.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/show_results.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_show.setIcon(icon3)
        self.btn_show.setIconSize(QtCore.QSize(64, 64))
        self.btn_show.setCheckable(True)
        self.btn_show.setAutoExclusive(True)
        self.btn_show.setAutoRaise(True)
        self.btn_show.setObjectName(_fromUtf8("btn_show"))
        self.horizontalLayout.addWidget(self.btn_show)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_about = QtGui.QToolButton(self.function_menu)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/help-about.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_about.setIcon(icon4)
        self.btn_about.setIconSize(QtCore.QSize(64, 64))
        self.btn_about.setCheckable(True)
        self.btn_about.setAutoExclusive(True)
        self.btn_about.setAutoRaise(True)
        self.btn_about.setObjectName(_fromUtf8("btn_about"))
        self.horizontalLayout.addWidget(self.btn_about)
        self.verticalLayout.addWidget(self.function_menu)
        self.main_screen = QtGui.QStackedWidget(self.centralwidget)
        self.main_screen.setObjectName(_fromUtf8("main_screen"))
        self.page_choose = QtGui.QWidget()
        self.page_choose.setObjectName(_fromUtf8("page_choose"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page_choose)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.grp_choose_files = QtGui.QGroupBox(self.page_choose)
        self.grp_choose_files.setObjectName(_fromUtf8("grp_choose_files"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.grp_choose_files)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.widget_3 = QtGui.QWidget(self.grp_choose_files)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.widget_4 = QtGui.QWidget(self.widget_3)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.widget_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.btn_file_add = QtGui.QPushButton(self.widget_4)
        self.btn_file_add.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/list-add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_file_add.setIcon(icon5)
        self.btn_file_add.setIconSize(QtCore.QSize(22, 22))
        self.btn_file_add.setFlat(True)
        self.btn_file_add.setObjectName(_fromUtf8("btn_file_add"))
        self.horizontalLayout_4.addWidget(self.btn_file_add)
        self.btn_file_remove = QtGui.QPushButton(self.widget_4)
        self.btn_file_remove.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/list-remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_file_remove.setIcon(icon6)
        self.btn_file_remove.setIconSize(QtCore.QSize(22, 22))
        self.btn_file_remove.setFlat(True)
        self.btn_file_remove.setObjectName(_fromUtf8("btn_file_remove"))
        self.horizontalLayout_4.addWidget(self.btn_file_remove)
        self.verticalLayout_7.addWidget(self.widget_4)
        self.gui_file_list = QtGui.QListView(self.widget_3)
        self.gui_file_list.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.gui_file_list.setObjectName(_fromUtf8("gui_file_list"))
        self.verticalLayout_7.addWidget(self.gui_file_list)
        self.horizontalLayout_3.addWidget(self.widget_3)
        self.widget = QtGui.QWidget(self.grp_choose_files)
        self.widget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_3.addWidget(self.widget)
        self.verticalLayout_2.addWidget(self.grp_choose_files)
        self.main_screen.addWidget(self.page_choose)
        self.page_analyze = QtGui.QWidget()
        self.page_analyze.setObjectName(_fromUtf8("page_analyze"))
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.page_analyze)
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.groupBox = QtGui.QGroupBox(self.page_analyze)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.btn_load_statistics = QtGui.QPushButton(self.groupBox)
        self.btn_load_statistics.setObjectName(_fromUtf8("btn_load_statistics"))
        self.gridLayout_2.addWidget(self.btn_load_statistics, 0, 0, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 5, 1, 1, 2)
        self.btn_add_check_combo = QtGui.QPushButton(self.groupBox_8)
        self.btn_add_check_combo.setEnabled(False)
        self.btn_add_check_combo.setObjectName(_fromUtf8("btn_add_check_combo"))
        self.gridLayout_3.addWidget(self.btn_add_check_combo, 5, 0, 1, 1)
        self.line_values_of_n = QtGui.QLineEdit(self.groupBox_8)
        self.line_values_of_n.setEnabled(False)
        self.line_values_of_n.setInputMask(_fromUtf8(""))
        self.line_values_of_n.setMaxLength(1024)
        self.line_values_of_n.setFrame(True)
        self.line_values_of_n.setObjectName(_fromUtf8("line_values_of_n"))
        self.gridLayout_3.addWidget(self.line_values_of_n, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_8)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.line_offset_interval = QtGui.QLineEdit(self.groupBox_8)
        self.line_offset_interval.setEnabled(False)
        self.line_offset_interval.setInputMask(_fromUtf8(""))
        self.line_offset_interval.setMaxLength(256)
        self.line_offset_interval.setObjectName(_fromUtf8("line_offset_interval"))
        self.gridLayout_3.addWidget(self.line_offset_interval, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_8)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.line_compare_these_parts = QtGui.QLineEdit(self.groupBox_8)
        self.line_compare_these_parts.setEnabled(False)
        self.line_compare_these_parts.setInputMask(_fromUtf8(""))
        self.line_compare_these_parts.setObjectName(_fromUtf8("line_compare_these_parts"))
        self.gridLayout_3.addWidget(self.line_compare_these_parts, 3, 1, 1, 2)
        self.label_7 = QtGui.QLabel(self.groupBox_8)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 3, 0, 1, 1)
        self.btn_choose_note = QtGui.QPushButton(self.groupBox_8)
        self.btn_choose_note.setEnabled(False)
        self.btn_choose_note.setObjectName(_fromUtf8("btn_choose_note"))
        self.gridLayout_3.addWidget(self.btn_choose_note, 1, 2, 1, 1)
        self.widget_2 = QtGui.QWidget(self.groupBox_8)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.widget_5 = QtGui.QWidget(self.widget_2)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.widget_5)
        self.verticalLayout_22.setMargin(0)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.chk_all_voice_combos = QtGui.QCheckBox(self.widget_5)
        self.chk_all_voice_combos.setEnabled(False)
        self.chk_all_voice_combos.setObjectName(_fromUtf8("chk_all_voice_combos"))
        self.verticalLayout_22.addWidget(self.chk_all_voice_combos)
        self.chk_basso_seguente = QtGui.QCheckBox(self.widget_5)
        self.chk_basso_seguente.setEnabled(False)
        self.chk_basso_seguente.setObjectName(_fromUtf8("chk_basso_seguente"))
        self.verticalLayout_22.addWidget(self.chk_basso_seguente)
        self.horizontalLayout_9.addWidget(self.widget_5)
        self.gridLayout_3.addWidget(self.widget_2, 4, 0, 1, 3)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 6, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_8, 0, 2, 2, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 1, 1, 1)
        self.gui_pieces_list = QtGui.QTableView(self.groupBox)
        self.gui_pieces_list.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.gui_pieces_list.setObjectName(_fromUtf8("gui_pieces_list"))
        self.gui_pieces_list.horizontalHeader().setMinimumSectionSize(2)
        self.gui_pieces_list.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.gui_pieces_list, 1, 0, 1, 2)
        self.verticalLayout_23.addWidget(self.groupBox)
        self.main_screen.addWidget(self.page_analyze)
        self.page_show = QtGui.QWidget()
        self.page_show.setObjectName(_fromUtf8("page_show"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page_show)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.page_show)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.rdo_chart = QtGui.QRadioButton(self.groupBox_5)
        self.rdo_chart.setChecked(True)
        self.rdo_chart.setObjectName(_fromUtf8("rdo_chart"))
        self.verticalLayout_9.addWidget(self.rdo_chart)
        self.rdo_score = QtGui.QRadioButton(self.groupBox_5)
        self.rdo_score.setObjectName(_fromUtf8("rdo_score"))
        self.verticalLayout_9.addWidget(self.rdo_score)
        self.rdo_targeted_score = QtGui.QRadioButton(self.groupBox_5)
        self.rdo_targeted_score.setObjectName(_fromUtf8("rdo_targeted_score"))
        self.verticalLayout_9.addWidget(self.rdo_targeted_score)
        self.rdo_list = QtGui.QRadioButton(self.groupBox_5)
        self.rdo_list.setObjectName(_fromUtf8("rdo_list"))
        self.verticalLayout_9.addWidget(self.rdo_list)
        self.gridLayout.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_n = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_n.setObjectName(_fromUtf8("groupBox_n"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_n)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.line_show_these_ns = QtGui.QLineEdit(self.groupBox_n)
        self.line_show_these_ns.setObjectName(_fromUtf8("line_show_these_ns"))
        self.verticalLayout_12.addWidget(self.line_show_these_ns)
        self.gridLayout.addWidget(self.groupBox_n, 0, 3, 1, 1)
        self.groupBox_sorted_by = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_sorted_by.setObjectName(_fromUtf8("groupBox_sorted_by"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.groupBox_sorted_by)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.rdo_frequency = QtGui.QRadioButton(self.groupBox_sorted_by)
        self.rdo_frequency.setChecked(True)
        self.rdo_frequency.setObjectName(_fromUtf8("rdo_frequency"))
        self.verticalLayout_16.addWidget(self.rdo_frequency)
        self.rdo_name = QtGui.QRadioButton(self.groupBox_sorted_by)
        self.rdo_name.setObjectName(_fromUtf8("rdo_name"))
        self.verticalLayout_16.addWidget(self.rdo_name)
        self.gridLayout.addWidget(self.groupBox_sorted_by, 3, 0, 1, 2)
        self.groupBox_10 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_10.setTitle(_fromUtf8(""))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_5 = QtGui.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_14.addWidget(self.label_5)
        self.line_output_most_common = QtGui.QLineEdit(self.groupBox_10)
        self.line_output_most_common.setObjectName(_fromUtf8("line_output_most_common"))
        self.verticalLayout_14.addWidget(self.line_output_most_common)
        self.lbl_most_common = QtGui.QLabel(self.groupBox_10)
        self.lbl_most_common.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_most_common.setObjectName(_fromUtf8("lbl_most_common"))
        self.verticalLayout_14.addWidget(self.lbl_most_common)
        self.gridLayout.addWidget(self.groupBox_10, 1, 0, 1, 2)
        self.groupBox_sort_order = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_sort_order.setObjectName(_fromUtf8("groupBox_sort_order"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.groupBox_sort_order)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.rdo_descending = QtGui.QRadioButton(self.groupBox_sort_order)
        self.rdo_descending.setChecked(True)
        self.rdo_descending.setObjectName(_fromUtf8("rdo_descending"))
        self.verticalLayout_17.addWidget(self.rdo_descending)
        self.rdo_ascending = QtGui.QRadioButton(self.groupBox_sort_order)
        self.rdo_ascending.setObjectName(_fromUtf8("rdo_ascending"))
        self.verticalLayout_17.addWidget(self.rdo_ascending)
        self.gridLayout.addWidget(self.groupBox_sort_order, 3, 2, 1, 2)
        self.groupBox_11 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_11.setTitle(_fromUtf8(""))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.lbl_exclude_if_fewer = QtGui.QLabel(self.groupBox_11)
        self.lbl_exclude_if_fewer.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_exclude_if_fewer.setObjectName(_fromUtf8("lbl_exclude_if_fewer"))
        self.verticalLayout_15.addWidget(self.lbl_exclude_if_fewer)
        self.line_threshold = QtGui.QLineEdit(self.groupBox_11)
        self.line_threshold.setObjectName(_fromUtf8("line_threshold"))
        self.verticalLayout_15.addWidget(self.line_threshold)
        self.label_8 = QtGui.QLabel(self.groupBox_11)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_15.addWidget(self.label_8)
        self.gridLayout.addWidget(self.groupBox_11, 1, 2, 1, 2)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.rdo_heedQuality = QtGui.QRadioButton(self.groupBox_6)
        self.rdo_heedQuality.setObjectName(_fromUtf8("rdo_heedQuality"))
        self.verticalLayout_10.addWidget(self.rdo_heedQuality)
        self.rdo_noHeedQuality = QtGui.QRadioButton(self.groupBox_6)
        self.rdo_noHeedQuality.setChecked(True)
        self.rdo_noHeedQuality.setObjectName(_fromUtf8("rdo_noHeedQuality"))
        self.verticalLayout_10.addWidget(self.rdo_noHeedQuality)
        self.gridLayout.addWidget(self.groupBox_6, 2, 2, 1, 2)
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.rdo_compound = QtGui.QRadioButton(self.groupBox_9)
        self.rdo_compound.setChecked(True)
        self.rdo_compound.setObjectName(_fromUtf8("rdo_compound"))
        self.verticalLayout_13.addWidget(self.rdo_compound)
        self.rdo_simple = QtGui.QRadioButton(self.groupBox_9)
        self.rdo_simple.setObjectName(_fromUtf8("rdo_simple"))
        self.verticalLayout_13.addWidget(self.rdo_simple)
        self.gridLayout.addWidget(self.groupBox_9, 2, 0, 1, 2)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.rdo_intervals = QtGui.QRadioButton(self.groupBox_7)
        self.rdo_intervals.setObjectName(_fromUtf8("rdo_intervals"))
        self.verticalLayout_11.addWidget(self.rdo_intervals)
        self.rdo_ngrams = QtGui.QRadioButton(self.groupBox_7)
        self.rdo_ngrams.setChecked(True)
        self.rdo_ngrams.setObjectName(_fromUtf8("rdo_ngrams"))
        self.verticalLayout_11.addWidget(self.rdo_ngrams)
        self.gridLayout.addWidget(self.groupBox_7, 0, 1, 1, 2)
        self.btn_show_results = QtGui.QPushButton(self.groupBox_2)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/show_checkmark.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_show_results.setIcon(icon7)
        self.btn_show_results.setIconSize(QtCore.QSize(64, 64))
        self.btn_show_results.setObjectName(_fromUtf8("btn_show_results"))
        self.gridLayout.addWidget(self.btn_show_results, 3, 5, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 3, 4, 1, 1)
        self.groupBox_targeted_score = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_targeted_score.setEnabled(False)
        self.groupBox_targeted_score.setObjectName(_fromUtf8("groupBox_targeted_score"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.groupBox_targeted_score)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_9 = QtGui.QLabel(self.groupBox_targeted_score)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_18.addWidget(self.label_9)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.line_ngram_in_colour = QtGui.QLineEdit(self.groupBox_targeted_score)
        self.line_ngram_in_colour.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.line_ngram_in_colour.setObjectName(_fromUtf8("line_ngram_in_colour"))
        self.horizontalLayout_2.addWidget(self.line_ngram_in_colour)
        self.btn_ngram_in_colour = QtGui.QPushButton(self.groupBox_targeted_score)
        self.btn_ngram_in_colour.setText(_fromUtf8(""))
        self.btn_ngram_in_colour.setIcon(icon5)
        self.btn_ngram_in_colour.setFlat(True)
        self.btn_ngram_in_colour.setObjectName(_fromUtf8("btn_ngram_in_colour"))
        self.horizontalLayout_2.addWidget(self.btn_ngram_in_colour)
        self.verticalLayout_18.addLayout(self.horizontalLayout_2)
        self.label_10 = QtGui.QLabel(self.groupBox_targeted_score)
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_18.addWidget(self.label_10)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.line_ngram_in_black = QtGui.QLineEdit(self.groupBox_targeted_score)
        self.line_ngram_in_black.setObjectName(_fromUtf8("line_ngram_in_black"))
        self.horizontalLayout_5.addWidget(self.line_ngram_in_black)
        self.btn_ngram_in_black = QtGui.QPushButton(self.groupBox_targeted_score)
        self.btn_ngram_in_black.setText(_fromUtf8(""))
        self.btn_ngram_in_black.setIcon(icon5)
        self.btn_ngram_in_black.setFlat(True)
        self.btn_ngram_in_black.setObjectName(_fromUtf8("btn_ngram_in_black"))
        self.horizontalLayout_5.addWidget(self.btn_ngram_in_black)
        self.verticalLayout_18.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_targeted_score)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.frame = QtGui.QFrame(self.groupBox_targeted_score)
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_6.addWidget(self.frame)
        self.verticalLayout_18.addLayout(self.horizontalLayout_6)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.groupBox_targeted_score)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.verticalLayout_18.addWidget(self.plainTextEdit)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem8)
        self.gridLayout.addWidget(self.groupBox_targeted_score, 0, 4, 3, 2)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.main_screen.addWidget(self.page_show)
        self.page_working = QtGui.QWidget()
        self.page_working.setObjectName(_fromUtf8("page_working"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.page_working)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem9)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.btn_wait_clock = QtGui.QPushButton(self.page_working)
        self.btn_wait_clock.setEnabled(True)
        self.btn_wait_clock.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/working.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_wait_clock.setIcon(icon8)
        self.btn_wait_clock.setIconSize(QtCore.QSize(64, 64))
        self.btn_wait_clock.setCheckable(False)
        self.btn_wait_clock.setChecked(False)
        self.btn_wait_clock.setFlat(True)
        self.btn_wait_clock.setObjectName(_fromUtf8("btn_wait_clock"))
        self.horizontalLayout_8.addWidget(self.btn_wait_clock)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.verticalLayout_21.addLayout(self.horizontalLayout_8)
        self.lbl_status_text = QtGui.QLabel(self.page_working)
        self.lbl_status_text.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lbl_status_text.setObjectName(_fromUtf8("lbl_status_text"))
        self.verticalLayout_21.addWidget(self.lbl_status_text)
        self.progress_bar = QtGui.QProgressBar(self.page_working)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName(_fromUtf8("progress_bar"))
        self.verticalLayout_21.addWidget(self.progress_bar)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem12)
        self.main_screen.addWidget(self.page_working)
        self.page_about = QtGui.QWidget()
        self.page_about.setObjectName(_fromUtf8("page_about"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page_about)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_4 = QtGui.QGroupBox(self.page_about)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label = QtGui.QLabel(self.groupBox_4)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_6.addWidget(self.label)
        self.line = QtGui.QFrame(self.groupBox_4)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_6.addWidget(self.line)
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_6.addWidget(self.label_2)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.main_screen.addWidget(self.page_about)
        self.verticalLayout.addWidget(self.main_screen)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.main_screen.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "vis", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_choose_files.setToolTip(QtGui.QApplication.translate("MainWindow", "Choose Files", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_step1.setToolTip(QtGui.QApplication.translate("MainWindow", "Continue to Step 2", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_analyze.setToolTip(QtGui.QApplication.translate("MainWindow", "Prepare and Assemble for Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_step2.setToolTip(QtGui.QApplication.translate("MainWindow", "Continue to the Step 3", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_show.setToolTip(QtGui.QApplication.translate("MainWindow", "Show and Save Results", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_about.setToolTip(QtGui.QApplication.translate("MainWindow", "About \"vis\"", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_choose_files.setTitle(QtGui.QApplication.translate("MainWindow", "Choose Files", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Files to Analyze:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_file_add.setToolTip(QtGui.QApplication.translate("MainWindow", "Add Files", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_file_remove.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove Selected Files", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Assemble Results, Statistics, Analyses", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_load_statistics.setText(QtGui.QApplication.translate("MainWindow", "Load Existing Statistics Database", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("MainWindow", "Settings for Piece", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_add_check_combo.setText(QtGui.QApplication.translate("MainWindow", "Add Combination", None, QtGui.QApplication.UnicodeUTF8))
        self.line_values_of_n.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Values of \'n\':", None, QtGui.QApplication.UnicodeUTF8))
        self.line_offset_interval.setText(QtGui.QApplication.translate("MainWindow", "0.5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Offset Interval:", None, QtGui.QApplication.UnicodeUTF8))
        self.line_compare_these_parts.setText(QtGui.QApplication.translate("MainWindow", "e.g., [0,3] or [[0,3],[1,3]]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Compare These Parts:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_choose_note.setText(QtGui.QApplication.translate("MainWindow", "Choose Offset Note", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_all_voice_combos.setToolTip(QtGui.QApplication.translate("MainWindow", "Collect Statistics for all Part Combinations", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_all_voice_combos.setText(QtGui.QApplication.translate("MainWindow", "All Combinations", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_basso_seguente.setToolTip(QtGui.QApplication.translate("MainWindow", "Generate Basso Seguente Part", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_basso_seguente.setText(QtGui.QApplication.translate("MainWindow", "Basso Seguente", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Show Results", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Output Format", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_chart.setText(QtGui.QApplication.translate("MainWindow", "Chart/Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_score.setText(QtGui.QApplication.translate("MainWindow", "Summary Score", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_targeted_score.setText(QtGui.QApplication.translate("MainWindow", "Targeted Score", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_list.setText(QtGui.QApplication.translate("MainWindow", "List", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_n.setTitle(QtGui.QApplication.translate("MainWindow", "Values of N", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_sorted_by.setTitle(QtGui.QApplication.translate("MainWindow", "Sorted by...", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_frequency.setText(QtGui.QApplication.translate("MainWindow", "frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_name.setText(QtGui.QApplication.translate("MainWindow", "n-gram", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Output the", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_most_common.setText(QtGui.QApplication.translate("MainWindow", "most common n-grams.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_sort_order.setTitle(QtGui.QApplication.translate("MainWindow", "Sort Order", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_descending.setText(QtGui.QApplication.translate("MainWindow", "Descending (High to Low)", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_ascending.setText(QtGui.QApplication.translate("MainWindow", "Ascending (Low to High)", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_exclude_if_fewer.setText(QtGui.QApplication.translate("MainWindow", "Exclude n-grams with fewer than", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "occurrences.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Interval Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_heedQuality.setText(QtGui.QApplication.translate("MainWindow", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_noHeedQuality.setText(QtGui.QApplication.translate("MainWindow", "Ignore", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("MainWindow", "Octaves", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_compound.setText(QtGui.QApplication.translate("MainWindow", "Compound Intervals", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_simple.setText(QtGui.QApplication.translate("MainWindow", "Simple Intervals", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "What to Display", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_intervals.setText(QtGui.QApplication.translate("MainWindow", "Intervals", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_ngrams.setText(QtGui.QApplication.translate("MainWindow", "N-grams", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_show_results.setText(QtGui.QApplication.translate("MainWindow", "Process and &Show", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_targeted_score.setTitle(QtGui.QApplication.translate("MainWindow", "Targeted Score", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Annotate this n-gram in colour:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Annotate this n-gram in black:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Choose Colour", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_wait_clock.setToolTip(QtGui.QApplication.translate("MainWindow", "Hi, mom!", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_status_text.setText(QtGui.QApplication.translate("MainWindow", "Please wait...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Information about vis", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" text-decoration: underline;\">vis (pre-Milestone 4)</span></p><p>Copyright (c) 2012 Christopher Antila and Jamie Klassen</p><p>This program is free software: you can redistribute it and/or modify<br/>it under the terms of the GNU General Public License as published by<br/>the Free Software Foundation, either version 3 of the License, or<br/>(at your option) any later version.</p><p>This program is distributed in the hope that it will be useful,<br/>but WITHOUT ANY WARRANTY; without even the implied warranty of<br/>MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the<br/>GNU General Public License for more details.</p><p>You should have received a copy of the GNU General Public License<br/>along with this program. If not, see &lt;http://www.gnu.org/licenses/&gt;.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>vis was written as part of McGill University\'s contribution to the ELVIS project.<br/>For more information about ELVIS, please refer to our <a href=\"http://elvis.music.mcgill.ca/\"><span style=\" text-decoration: underline; color:#0057ae;\">web site</span></a>.</p><p>Funding for ELVIS was provided by the following organizations:<br/>- SSHRC (Social Sciences and Humanities Research Council) of Canada<br/>- NEH (National Endowment for the Humanities) of the United States of America<br/>- The Digging into Data Challenge</p><p>vis is written in the Python programming language, and relies on the following<br/>software, all released under free licences:<br/>- <a href=\"http://mit.edu/music21/\"><span style=\" text-decoration: underline; color:#0057ae;\">music21<br/></span></a>- <a href=\"http://www.riverbankcomputing.co.uk/software/pyqt/download\"><span style=\" text-decoration: underline; color:#0057ae;\">PyQt4</span></a><br/>- <a href=\"http://www.oxygen-icons.org/\"><span style=\" text-decoration: underline; color:#0057ae;\">Oxygen Icons</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

