# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/christo/ELVIS/programs/vis/qt/main_window.ui'
#
# Created: Mon Aug 13 16:31:05 2012
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(523, 426)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(520, 426))
        MainWindow.setWindowTitle("vis")
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabs_main = QtGui.QTabWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs_main.sizePolicy().hasHeightForWidth())
        self.tabs_main.setSizePolicy(sizePolicy)
        self.tabs_main.setMinimumSize(QtCore.QSize(501, 261))
        self.tabs_main.setAutoFillBackground(True)
        self.tabs_main.setTabPosition(QtGui.QTabWidget.West)
        self.tabs_main.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabs_main.setDocumentMode(False)
        self.tabs_main.setObjectName("tabs_main")
        self.tab_settings = QtGui.QWidget()
        self.tab_settings.setObjectName("tab_settings")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_settings)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabs_settings = QtGui.QTabWidget(self.tab_settings)
        self.tabs_settings.setMinimumSize(QtCore.QSize(472, 402))
        self.tabs_settings.setObjectName("tabs_settings")
        self.tab_usual_settings = QtGui.QWidget()
        self.tab_usual_settings.setObjectName("tab_usual_settings")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_usual_settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_heedQuality = QtGui.QGroupBox(self.tab_usual_settings)
        self.groupBox_heedQuality.setMinimumSize(QtCore.QSize(141, 81))
        self.groupBox_heedQuality.setObjectName("groupBox_heedQuality")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_heedQuality)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.rdo_heedQuality = QtGui.QRadioButton(self.groupBox_heedQuality)
        self.rdo_heedQuality.setObjectName("rdo_heedQuality")
        self.verticalLayout_5.addWidget(self.rdo_heedQuality)
        self.rdo_ignoreQuality = QtGui.QRadioButton(self.groupBox_heedQuality)
        self.rdo_ignoreQuality.setChecked(True)
        self.rdo_ignoreQuality.setObjectName("rdo_ignoreQuality")
        self.verticalLayout_5.addWidget(self.rdo_ignoreQuality)
        self.verticalLayout.addWidget(self.groupBox_heedQuality)
        self.groupBox_Octaves = QtGui.QGroupBox(self.tab_usual_settings)
        self.groupBox_Octaves.setMinimumSize(QtCore.QSize(201, 87))
        self.groupBox_Octaves.setObjectName("groupBox_Octaves")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_Octaves)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.rdo_compoundIntervals = QtGui.QRadioButton(self.groupBox_Octaves)
        self.rdo_compoundIntervals.setChecked(True)
        self.rdo_compoundIntervals.setObjectName("rdo_compoundIntervals")
        self.verticalLayout_6.addWidget(self.rdo_compoundIntervals)
        self.rdo_simpleIntervals = QtGui.QRadioButton(self.groupBox_Octaves)
        self.rdo_simpleIntervals.setObjectName("rdo_simpleIntervals")
        self.verticalLayout_6.addWidget(self.rdo_simpleIntervals)
        self.verticalLayout.addWidget(self.groupBox_Octaves)
        self.groupBoxwhichNs = QtGui.QGroupBox(self.tab_usual_settings)
        self.groupBoxwhichNs.setMinimumSize(QtCore.QSize(191, 71))
        self.groupBoxwhichNs.setObjectName("groupBoxwhichNs")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBoxwhichNs)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.groupBoxwhichNs)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.line_n = QtGui.QLineEdit(self.groupBoxwhichNs)
        self.line_n.setText("2")
        self.line_n.setMaxLength(20)
        self.line_n.setObjectName("line_n")
        self.horizontalLayout_2.addWidget(self.line_n)
        self.btn_setN = QtGui.QPushButton(self.groupBoxwhichNs)
        self.btn_setN.setObjectName("btn_setN")
        self.horizontalLayout_2.addWidget(self.btn_setN)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.groupBoxwhichNs)
        self.groupBox_LilyPond = QtGui.QGroupBox(self.tab_usual_settings)
        self.groupBox_LilyPond.setMinimumSize(QtCore.QSize(211, 81))
        self.groupBox_LilyPond.setObjectName("groupBox_LilyPond")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_LilyPond)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.rdo_yesScore = QtGui.QRadioButton(self.groupBox_LilyPond)
        self.rdo_yesScore.setObjectName("rdo_yesScore")
        self.verticalLayout_8.addWidget(self.rdo_yesScore)
        self.rdo_noScore = QtGui.QRadioButton(self.groupBox_LilyPond)
        self.rdo_noScore.setChecked(True)
        self.rdo_noScore.setObjectName("rdo_noScore")
        self.verticalLayout_8.addWidget(self.rdo_noScore)
        self.verticalLayout.addWidget(self.groupBox_LilyPond)
        self.tabs_settings.addTab(self.tab_usual_settings, "")
        self.tab_obscure_settings = QtGui.QWidget()
        self.tab_obscure_settings.setObjectName("tab_obscure_settings")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_obscure_settings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_Offsets = QtGui.QGroupBox(self.tab_obscure_settings)
        self.groupBox_Offsets.setObjectName("groupBox_Offsets")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_Offsets)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.groupBox_Offsets)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.line_intervalOffset = QtGui.QLineEdit(self.groupBox_Offsets)
        self.line_intervalOffset.setText("0.5")
        self.line_intervalOffset.setMaxLength(6)
        self.line_intervalOffset.setObjectName("line_intervalOffset")
        self.horizontalLayout.addWidget(self.line_intervalOffset)
        self.btn_setOffset = QtGui.QPushButton(self.groupBox_Offsets)
        self.btn_setOffset.setObjectName("btn_setOffset")
        self.horizontalLayout.addWidget(self.btn_setOffset)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox_Offsets)
        self.tabs_settings.addTab(self.tab_obscure_settings, "")
        self.verticalLayout_3.addWidget(self.tabs_settings)
        self.tabs_main.addTab(self.tab_settings, "")
        self.tab_input = QtGui.QWidget()
        self.tab_input.setObjectName("tab_input")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_input)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtGui.QLabel(self.tab_input)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.btn_chooseFiles = QtGui.QPushButton(self.tab_input)
        self.btn_chooseFiles.setObjectName("btn_chooseFiles")
        self.verticalLayout_4.addWidget(self.btn_chooseFiles)
        self.btn_chooseDirectories = QtGui.QPushButton(self.tab_input)
        self.btn_chooseDirectories.setObjectName("btn_chooseDirectories")
        self.verticalLayout_4.addWidget(self.btn_chooseDirectories)
        self.txt_filenames = QtGui.QPlainTextEdit(self.tab_input)
        self.txt_filenames.setUndoRedoEnabled(False)
        self.txt_filenames.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.txt_filenames.setObjectName("txt_filenames")
        self.verticalLayout_4.addWidget(self.txt_filenames)
        self.btn_analyze = QtGui.QPushButton(self.tab_input)
        self.btn_analyze.setObjectName("btn_analyze")
        self.verticalLayout_4.addWidget(self.btn_analyze)
        self.tabs_main.addTab(self.tab_input, "")
        self.tab_output = QtGui.QWidget()
        self.tab_output.setObjectName("tab_output")
        self.txt_results = QtGui.QPlainTextEdit(self.tab_output)
        self.txt_results.setGeometry(QtCore.QRect(10, 10, 461, 391))
        self.txt_results.setPlainText("Beep")
        self.txt_results.setBackgroundVisible(False)
        self.txt_results.setObjectName("txt_results")
        self.tabs_main.addTab(self.tab_output, "")
        self.gridLayout.addWidget(self.tabs_main, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.label_2.setBuddy(self.line_n)
        self.label.setBuddy(self.line_intervalOffset)

        self.retranslateUi(MainWindow)
        self.tabs_main.setCurrentIndex(1)
        self.tabs_settings.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.groupBox_heedQuality.setTitle(QtGui.QApplication.translate("MainWindow", "Interval Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_heedQuality.setText(QtGui.QApplication.translate("MainWindow", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_ignoreQuality.setText(QtGui.QApplication.translate("MainWindow", "Ignore", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Octaves.setTitle(QtGui.QApplication.translate("MainWindow", "Octaves", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_compoundIntervals.setText(QtGui.QApplication.translate("MainWindow", "Compound Intervals", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_simpleIntervals.setText(QtGui.QApplication.translate("MainWindow", "Simple Intervals", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxwhichNs.setTitle(QtGui.QApplication.translate("MainWindow", "Which Values of n?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "n = ", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_setN.setText(QtGui.QApplication.translate("MainWindow", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_LilyPond.setTitle(QtGui.QApplication.translate("MainWindow", "LilyPond", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_yesScore.setText(QtGui.QApplication.translate("MainWindow", "Produce Score", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_noScore.setText(QtGui.QApplication.translate("MainWindow", "Do not Produce Score", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_settings.setTabText(self.tabs_settings.indexOf(self.tab_usual_settings), QtGui.QApplication.translate("MainWindow", "Usual Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Offsets.setTitle(QtGui.QApplication.translate("MainWindow", "Offsets", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Offset between Intervals:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_setOffset.setText(QtGui.QApplication.translate("MainWindow", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_settings.setTabText(self.tabs_settings.indexOf(self.tab_obscure_settings), QtGui.QApplication.translate("MainWindow", "Obscure Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_main.setTabText(self.tabs_main.indexOf(self.tab_settings), QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Filenames to Analyze.\n"
"Please include one file name or directory per line.", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_chooseFiles.setText(QtGui.QApplication.translate("MainWindow", "Choose Files", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_chooseDirectories.setText(QtGui.QApplication.translate("MainWindow", "Choose Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_analyze.setText(QtGui.QApplication.translate("MainWindow", "Analyze!", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_main.setTabText(self.tabs_main.indexOf(self.tab_input), QtGui.QApplication.translate("MainWindow", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_main.setTabText(self.tabs_main.indexOf(self.tab_output), QtGui.QApplication.translate("MainWindow", "Show", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

