# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/christo/ELVIS/programs/vis/qt/main_window.ui'
#
# Created: Thu Aug 16 02:30:54 2012
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(636, 666)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(520, 426))
        MainWindow.setWindowTitle("vis")
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.tabs_main = QtGui.QTabWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs_main.sizePolicy().hasHeightForWidth())
        self.tabs_main.setSizePolicy(sizePolicy)
        self.tabs_main.setMinimumSize(QtCore.QSize(501, 261))
        self.tabs_main.setAutoFillBackground(True)
        self.tabs_main.setTabPosition(QtGui.QTabWidget.West)
        self.tabs_main.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabs_main.setDocumentMode(False)
        self.tabs_main.setObjectName("tabs_main")
        self.tab_settings = QtGui.QWidget()
        self.tab_settings.setObjectName("tab_settings")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_settings)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabs_settings = QtGui.QTabWidget(self.tab_settings)
        self.tabs_settings.setMinimumSize(QtCore.QSize(472, 402))
        self.tabs_settings.setObjectName("tabs_settings")
        self.tab_usual_settings = QtGui.QWidget()
        self.tab_usual_settings.setObjectName("tab_usual_settings")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_usual_settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_heedQuality = QtGui.QGroupBox(self.tab_usual_settings)
        self.groupBox_heedQuality.setMinimumSize(QtCore.QSize(141, 81))
        self.groupBox_heedQuality.setObjectName("groupBox_heedQuality")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_heedQuality)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.rdo_heedQuality = QtGui.QRadioButton(self.groupBox_heedQuality)
        self.rdo_heedQuality.setObjectName("rdo_heedQuality")
        self.verticalLayout_5.addWidget(self.rdo_heedQuality)
        self.rdo_ignoreQuality = QtGui.QRadioButton(self.groupBox_heedQuality)
        self.rdo_ignoreQuality.setChecked(True)
        self.rdo_ignoreQuality.setObjectName("rdo_ignoreQuality")
        self.verticalLayout_5.addWidget(self.rdo_ignoreQuality)
        self.verticalLayout.addWidget(self.groupBox_heedQuality)
        self.groupBox_Octaves = QtGui.QGroupBox(self.tab_usual_settings)
        self.groupBox_Octaves.setMinimumSize(QtCore.QSize(201, 87))
        self.groupBox_Octaves.setObjectName("groupBox_Octaves")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_Octaves)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.rdo_compoundIntervals = QtGui.QRadioButton(self.groupBox_Octaves)
        self.rdo_compoundIntervals.setChecked(True)
        self.rdo_compoundIntervals.setObjectName("rdo_compoundIntervals")
        self.verticalLayout_6.addWidget(self.rdo_compoundIntervals)
        self.rdo_simpleIntervals = QtGui.QRadioButton(self.groupBox_Octaves)
        self.rdo_simpleIntervals.setObjectName("rdo_simpleIntervals")
        self.verticalLayout_6.addWidget(self.rdo_simpleIntervals)
        self.verticalLayout.addWidget(self.groupBox_Octaves)
        self.groupBoxwhichNs = QtGui.QGroupBox(self.tab_usual_settings)
        self.groupBoxwhichNs.setMinimumSize(QtCore.QSize(191, 71))
        self.groupBoxwhichNs.setObjectName("groupBoxwhichNs")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBoxwhichNs)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.groupBoxwhichNs)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.line_n = QtGui.QLineEdit(self.groupBoxwhichNs)
        self.line_n.setText("2")
        self.line_n.setMaxLength(20)
        self.line_n.setObjectName("line_n")
        self.horizontalLayout_2.addWidget(self.line_n)
        self.btn_setN = QtGui.QPushButton(self.groupBoxwhichNs)
        self.btn_setN.setObjectName("btn_setN")
        self.horizontalLayout_2.addWidget(self.btn_setN)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.groupBoxwhichNs)
        self.groupBox_LilyPond = QtGui.QGroupBox(self.tab_usual_settings)
        self.groupBox_LilyPond.setMinimumSize(QtCore.QSize(211, 81))
        self.groupBox_LilyPond.setObjectName("groupBox_LilyPond")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_LilyPond)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.rdo_yesScore = QtGui.QRadioButton(self.groupBox_LilyPond)
        self.rdo_yesScore.setObjectName("rdo_yesScore")
        self.verticalLayout_8.addWidget(self.rdo_yesScore)
        self.rdo_noScore = QtGui.QRadioButton(self.groupBox_LilyPond)
        self.rdo_noScore.setChecked(True)
        self.rdo_noScore.setObjectName("rdo_noScore")
        self.verticalLayout_8.addWidget(self.rdo_noScore)
        self.verticalLayout.addWidget(self.groupBox_LilyPond)
        self.tabs_settings.addTab(self.tab_usual_settings, "")
        self.tab_obscure_settings = QtGui.QWidget()
        self.tab_obscure_settings.setObjectName("tab_obscure_settings")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_obscure_settings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_Offsets = QtGui.QGroupBox(self.tab_obscure_settings)
        self.groupBox_Offsets.setObjectName("groupBox_Offsets")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_Offsets)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.groupBox_Offsets)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.line_intervalOffset = QtGui.QLineEdit(self.groupBox_Offsets)
        self.line_intervalOffset.setText("0.5")
        self.line_intervalOffset.setMaxLength(6)
        self.line_intervalOffset.setObjectName("line_intervalOffset")
        self.horizontalLayout.addWidget(self.line_intervalOffset)
        self.btn_setOffset = QtGui.QPushButton(self.groupBox_Offsets)
        self.btn_setOffset.setObjectName("btn_setOffset")
        self.horizontalLayout.addWidget(self.btn_setOffset)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox_Offsets)
        self.tabs_settings.addTab(self.tab_obscure_settings, "")
        self.verticalLayout_3.addWidget(self.tabs_settings)
        self.tabs_main.addTab(self.tab_settings, "")
        self.tab_input = QtGui.QWidget()
        self.tab_input.setObjectName("tab_input")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_input)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtGui.QLabel(self.tab_input)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.btn_chooseFiles = QtGui.QPushButton(self.tab_input)
        self.btn_chooseFiles.setObjectName("btn_chooseFiles")
        self.verticalLayout_4.addWidget(self.btn_chooseFiles)
        self.btn_chooseDirectories = QtGui.QPushButton(self.tab_input)
        self.btn_chooseDirectories.setObjectName("btn_chooseDirectories")
        self.verticalLayout_4.addWidget(self.btn_chooseDirectories)
        self.txt_filenames = QtGui.QPlainTextEdit(self.tab_input)
        self.txt_filenames.setUndoRedoEnabled(False)
        self.txt_filenames.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.txt_filenames.setObjectName("txt_filenames")
        self.verticalLayout_4.addWidget(self.txt_filenames)
        self.btn_analyze = QtGui.QPushButton(self.tab_input)
        self.btn_analyze.setObjectName("btn_analyze")
        self.verticalLayout_4.addWidget(self.btn_analyze)
        self.tabs_main.addTab(self.tab_input, "")
        self.tab_output = QtGui.QWidget()
        self.tab_output.setObjectName("tab_output")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab_output)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tabs_output_options = QtGui.QTabWidget(self.tab_output)
        self.tabs_output_options.setObjectName("tabs_output_options")
        self.tab_intervals = QtGui.QWidget()
        self.tab_intervals.setObjectName("tab_intervals")
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_intervals)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtGui.QGroupBox(self.tab_intervals)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.rdo_ascending_intervals = QtGui.QRadioButton(self.groupBox)
        self.rdo_ascending_intervals.setObjectName("rdo_ascending_intervals")
        self.verticalLayout_13.addWidget(self.rdo_ascending_intervals)
        self.rdo_descending_intervals = QtGui.QRadioButton(self.groupBox)
        self.rdo_descending_intervals.setChecked(True)
        self.rdo_descending_intervals.setObjectName("rdo_descending_intervals")
        self.verticalLayout_13.addWidget(self.rdo_descending_intervals)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_intervals)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.rdo_intervals_by_interval = QtGui.QRadioButton(self.groupBox_2)
        self.rdo_intervals_by_interval.setObjectName("rdo_intervals_by_interval")
        self.verticalLayout_14.addWidget(self.rdo_intervals_by_interval)
        self.rdo_intervals_by_frequency = QtGui.QRadioButton(self.groupBox_2)
        self.rdo_intervals_by_frequency.setChecked(True)
        self.rdo_intervals_by_frequency.setObjectName("rdo_intervals_by_frequency")
        self.verticalLayout_14.addWidget(self.rdo_intervals_by_frequency)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_intervals)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.chk_graph_intervals = QtGui.QCheckBox(self.groupBox_3)
        self.chk_graph_intervals.setObjectName("chk_graph_intervals")
        self.verticalLayout_11.addWidget(self.chk_graph_intervals)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.widget = QtGui.QWidget(self.tab_intervals)
        self.widget.setObjectName("widget")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.btn_show_intervals = QtGui.QPushButton(self.widget)
        self.btn_show_intervals.setObjectName("btn_show_intervals")
        self.verticalLayout_12.addWidget(self.btn_show_intervals)
        self.btn_save_intervals = QtGui.QPushButton(self.widget)
        self.btn_save_intervals.setObjectName("btn_save_intervals")
        self.verticalLayout_12.addWidget(self.btn_save_intervals)
        self.gridLayout_2.addWidget(self.widget, 1, 1, 1, 1)
        self.tabs_output_options.addTab(self.tab_intervals, "")
        self.tab_triangles = QtGui.QWidget()
        self.tab_triangles.setObjectName("tab_triangles")
        self.gridLayout = QtGui.QGridLayout(self.tab_triangles)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_4 = QtGui.QGroupBox(self.tab_triangles)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.rdo_ascending_triangles = QtGui.QRadioButton(self.groupBox_4)
        self.rdo_ascending_triangles.setObjectName("rdo_ascending_triangles")
        self.verticalLayout_20.addWidget(self.rdo_ascending_triangles)
        self.rdo_descending_triangles = QtGui.QRadioButton(self.groupBox_4)
        self.rdo_descending_triangles.setChecked(True)
        self.rdo_descending_triangles.setObjectName("rdo_descending_triangles")
        self.verticalLayout_20.addWidget(self.rdo_descending_triangles)
        self.gridLayout.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_triangles)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.rdo_ngrams_by_ngram = QtGui.QRadioButton(self.groupBox_5)
        self.rdo_ngrams_by_ngram.setObjectName("rdo_ngrams_by_ngram")
        self.verticalLayout_21.addWidget(self.rdo_ngrams_by_ngram)
        self.rdo_ngrams_by_freq = QtGui.QRadioButton(self.groupBox_5)
        self.rdo_ngrams_by_freq.setChecked(True)
        self.rdo_ngrams_by_freq.setObjectName("rdo_ngrams_by_freq")
        self.verticalLayout_21.addWidget(self.rdo_ngrams_by_freq)
        self.gridLayout.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_triangles)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.chk_graph_triangles = QtGui.QCheckBox(self.groupBox_6)
        self.chk_graph_triangles.setObjectName("chk_graph_triangles")
        self.verticalLayout_22.addWidget(self.chk_graph_triangles)
        self.gridLayout.addWidget(self.groupBox_6, 0, 1, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_triangles)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_24 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.widget_3 = QtGui.QWidget(self.groupBox_7)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtGui.QLabel(self.widget_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.line_show_triangles_n = QtGui.QLineEdit(self.widget_3)
        self.line_show_triangles_n.setMaxLength(20)
        self.line_show_triangles_n.setObjectName("line_show_triangles_n")
        self.horizontalLayout_4.addWidget(self.line_show_triangles_n)
        self.verticalLayout_24.addWidget(self.widget_3)
        self.btn_auto_n = QtGui.QPushButton(self.groupBox_7)
        self.btn_auto_n.setObjectName("btn_auto_n")
        self.verticalLayout_24.addWidget(self.btn_auto_n)
        self.gridLayout.addWidget(self.groupBox_7, 1, 1, 1, 1)
        self.widget_2 = QtGui.QWidget(self.tab_triangles)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_show_triangles = QtGui.QPushButton(self.widget_2)
        self.btn_show_triangles.setObjectName("btn_show_triangles")
        self.horizontalLayout_3.addWidget(self.btn_show_triangles)
        self.btn_save_triangles = QtGui.QPushButton(self.widget_2)
        self.btn_save_triangles.setObjectName("btn_save_triangles")
        self.horizontalLayout_3.addWidget(self.btn_save_triangles)
        self.gridLayout.addWidget(self.widget_2, 2, 0, 1, 2)
        self.tabs_output_options.addTab(self.tab_triangles, "")
        self.tab_score = QtGui.QWidget()
        self.tab_score.setObjectName("tab_score")
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.tab_score)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_5 = QtGui.QLabel(self.tab_score)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_23.addWidget(self.label_5)
        self.score_slider = QtGui.QSlider(self.tab_score)
        self.score_slider.setMaximum(100)
        self.score_slider.setOrientation(QtCore.Qt.Horizontal)
        self.score_slider.setInvertedAppearance(False)
        self.score_slider.setTickPosition(QtGui.QSlider.NoTicks)
        self.score_slider.setObjectName("score_slider")
        self.verticalLayout_23.addWidget(self.score_slider)
        self.score_progress = QtGui.QProgressBar(self.tab_score)
        self.score_progress.setProperty("value", 0)
        self.score_progress.setObjectName("score_progress")
        self.verticalLayout_23.addWidget(self.score_progress)
        self.tabs_output_options.addTab(self.tab_score, "")
        self.verticalLayout_10.addWidget(self.tabs_output_options)
        self.txt_results = QtGui.QPlainTextEdit(self.tab_output)
        self.txt_results.setBackgroundVisible(False)
        self.txt_results.setObjectName("txt_results")
        self.verticalLayout_10.addWidget(self.txt_results)
        self.tabs_main.addTab(self.tab_output, "")
        self.verticalLayout_19.addWidget(self.tabs_main)
        MainWindow.setCentralWidget(self.centralWidget)
        self.label_2.setBuddy(self.line_n)
        self.label.setBuddy(self.line_intervalOffset)
        self.label_4.setBuddy(self.line_show_triangles_n)

        self.retranslateUi(MainWindow)
        self.tabs_main.setCurrentIndex(2)
        self.tabs_settings.setCurrentIndex(0)
        self.tabs_output_options.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.groupBox_heedQuality.setTitle(QtGui.QApplication.translate("MainWindow", "Interval Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_heedQuality.setText(QtGui.QApplication.translate("MainWindow", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_ignoreQuality.setText(QtGui.QApplication.translate("MainWindow", "Ignore", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Octaves.setTitle(QtGui.QApplication.translate("MainWindow", "Octaves", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_compoundIntervals.setText(QtGui.QApplication.translate("MainWindow", "Compound Intervals", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_simpleIntervals.setText(QtGui.QApplication.translate("MainWindow", "Simple Intervals", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxwhichNs.setTitle(QtGui.QApplication.translate("MainWindow", "Which Values of n?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "n = ", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_setN.setText(QtGui.QApplication.translate("MainWindow", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_LilyPond.setTitle(QtGui.QApplication.translate("MainWindow", "LilyPond", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_yesScore.setText(QtGui.QApplication.translate("MainWindow", "Produce Score", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_noScore.setText(QtGui.QApplication.translate("MainWindow", "Do not Produce Score", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_settings.setTabText(self.tabs_settings.indexOf(self.tab_usual_settings), QtGui.QApplication.translate("MainWindow", "Usual Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Offsets.setTitle(QtGui.QApplication.translate("MainWindow", "Offsets", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Offset between Intervals:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_setOffset.setText(QtGui.QApplication.translate("MainWindow", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_settings.setTabText(self.tabs_settings.indexOf(self.tab_obscure_settings), QtGui.QApplication.translate("MainWindow", "Obscure Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_main.setTabText(self.tabs_main.indexOf(self.tab_settings), QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Filenames to Analyze.\n"
"Please include one file name or directory per line.", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_chooseFiles.setText(QtGui.QApplication.translate("MainWindow", "Choose Files", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_chooseDirectories.setText(QtGui.QApplication.translate("MainWindow", "Choose Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_analyze.setText(QtGui.QApplication.translate("MainWindow", "Analyze!", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_main.setTabText(self.tabs_main.indexOf(self.tab_input), QtGui.QApplication.translate("MainWindow", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Sort Order", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_ascending_intervals.setText(QtGui.QApplication.translate("MainWindow", "Low to High (Ascending)", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_descending_intervals.setText(QtGui.QApplication.translate("MainWindow", "High to Low (Descending)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Sort Object", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_intervals_by_interval.setText(QtGui.QApplication.translate("MainWindow", "By Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_intervals_by_frequency.setText(QtGui.QApplication.translate("MainWindow", "By Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_graph_intervals.setToolTip(QtGui.QApplication.translate("MainWindow", "Output results as a chart rather than a list", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_graph_intervals.setText(QtGui.QApplication.translate("MainWindow", "Produce Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_show_intervals.setToolTip(QtGui.QApplication.translate("MainWindow", "Display results below (list), or in a new window (graph)", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_show_intervals.setText(QtGui.QApplication.translate("MainWindow", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save_intervals.setToolTip(QtGui.QApplication.translate("MainWindow", "Save results to a file", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save_intervals.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_output_options.setTabText(self.tabs_output_options.indexOf(self.tab_intervals), QtGui.QApplication.translate("MainWindow", "Intervals", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Sort Order", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_ascending_triangles.setText(QtGui.QApplication.translate("MainWindow", "Low to High (Ascending)", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_descending_triangles.setText(QtGui.QApplication.translate("MainWindow", "High to Low (Descending)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Sort Object", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_ngrams_by_ngram.setText(QtGui.QApplication.translate("MainWindow", "By Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_ngrams_by_freq.setText(QtGui.QApplication.translate("MainWindow", "By Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_graph_triangles.setText(QtGui.QApplication.translate("MainWindow", "Produce Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Cardinalities", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "n = ", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_auto_n.setText(QtGui.QApplication.translate("MainWindow", "Auto Fill", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_show_triangles.setText(QtGui.QApplication.translate("MainWindow", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save_triangles.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_output_options.setTabText(self.tabs_output_options.indexOf(self.tab_triangles), QtGui.QApplication.translate("MainWindow", "Triangles", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "How much money?", None, QtGui.QApplication.UnicodeUTF8))
        self.score_progress.setFormat(QtGui.QApplication.translate("MainWindow", "$%p", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_output_options.setTabText(self.tabs_output_options.indexOf(self.tab_score), QtGui.QApplication.translate("MainWindow", "Score", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_main.setTabText(self.tabs_main.indexOf(self.tab_output), QtGui.QApplication.translate("MainWindow", "Show", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

