# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/crantila/Documents/ELVIS/programs/vis/qt/main_window.ui'
#
# Created: Tue Aug 28 23:36:58 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(636, 666)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(520, 426))
        MainWindow.setWindowTitle(_fromUtf8("vis"))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.tabs_main = QtGui.QTabWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs_main.sizePolicy().hasHeightForWidth())
        self.tabs_main.setSizePolicy(sizePolicy)
        self.tabs_main.setMinimumSize(QtCore.QSize(501, 261))
        self.tabs_main.setAutoFillBackground(True)
        self.tabs_main.setTabPosition(QtGui.QTabWidget.West)
        self.tabs_main.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabs_main.setDocumentMode(False)
        self.tabs_main.setObjectName(_fromUtf8("tabs_main"))
        self.tab_settings = QtGui.QWidget()
        self.tab_settings.setObjectName(_fromUtf8("tab_settings"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_settings)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabs_settings = QtGui.QTabWidget(self.tab_settings)
        self.tabs_settings.setMinimumSize(QtCore.QSize(472, 402))
        self.tabs_settings.setObjectName(_fromUtf8("tabs_settings"))
        self.tab_usual_settings = QtGui.QWidget()
        self.tab_usual_settings.setObjectName(_fromUtf8("tab_usual_settings"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_usual_settings)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_heedQuality = QtGui.QGroupBox(self.tab_usual_settings)
        self.groupBox_heedQuality.setMinimumSize(QtCore.QSize(141, 81))
        self.groupBox_heedQuality.setObjectName(_fromUtf8("groupBox_heedQuality"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_heedQuality)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.rdo_heedQuality = QtGui.QRadioButton(self.groupBox_heedQuality)
        self.rdo_heedQuality.setObjectName(_fromUtf8("rdo_heedQuality"))
        self.verticalLayout_5.addWidget(self.rdo_heedQuality)
        self.rdo_ignoreQuality = QtGui.QRadioButton(self.groupBox_heedQuality)
        self.rdo_ignoreQuality.setChecked(True)
        self.rdo_ignoreQuality.setObjectName(_fromUtf8("rdo_ignoreQuality"))
        self.verticalLayout_5.addWidget(self.rdo_ignoreQuality)
        self.verticalLayout.addWidget(self.groupBox_heedQuality)
        self.groupBox_Octaves = QtGui.QGroupBox(self.tab_usual_settings)
        self.groupBox_Octaves.setMinimumSize(QtCore.QSize(201, 87))
        self.groupBox_Octaves.setObjectName(_fromUtf8("groupBox_Octaves"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_Octaves)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.rdo_compoundIntervals = QtGui.QRadioButton(self.groupBox_Octaves)
        self.rdo_compoundIntervals.setChecked(True)
        self.rdo_compoundIntervals.setObjectName(_fromUtf8("rdo_compoundIntervals"))
        self.verticalLayout_6.addWidget(self.rdo_compoundIntervals)
        self.rdo_simpleIntervals = QtGui.QRadioButton(self.groupBox_Octaves)
        self.rdo_simpleIntervals.setObjectName(_fromUtf8("rdo_simpleIntervals"))
        self.verticalLayout_6.addWidget(self.rdo_simpleIntervals)
        self.verticalLayout.addWidget(self.groupBox_Octaves)
        self.groupBox_9 = QtGui.QGroupBox(self.tab_usual_settings)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.rdo_choose_every_file = QtGui.QRadioButton(self.groupBox_9)
        self.rdo_choose_every_file.setChecked(False)
        self.rdo_choose_every_file.setObjectName(_fromUtf8("rdo_choose_every_file"))
        self.verticalLayout_16.addWidget(self.rdo_choose_every_file)
        self.rdo_choose_just_once = QtGui.QRadioButton(self.groupBox_9)
        self.rdo_choose_just_once.setChecked(True)
        self.rdo_choose_just_once.setObjectName(_fromUtf8("rdo_choose_just_once"))
        self.verticalLayout_16.addWidget(self.rdo_choose_just_once)
        self.verticalLayout.addWidget(self.groupBox_9)
        self.groupBoxwhichNs = QtGui.QGroupBox(self.tab_usual_settings)
        self.groupBoxwhichNs.setMinimumSize(QtCore.QSize(191, 71))
        self.groupBoxwhichNs.setObjectName(_fromUtf8("groupBoxwhichNs"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBoxwhichNs)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBoxwhichNs)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.line_n = QtGui.QLineEdit(self.groupBoxwhichNs)
        self.line_n.setText(_fromUtf8("2"))
        self.line_n.setMaxLength(20)
        self.line_n.setObjectName(_fromUtf8("line_n"))
        self.horizontalLayout_2.addWidget(self.line_n)
        self.btn_setN = QtGui.QPushButton(self.groupBoxwhichNs)
        self.btn_setN.setObjectName(_fromUtf8("btn_setN"))
        self.horizontalLayout_2.addWidget(self.btn_setN)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.groupBoxwhichNs)
        self.groupBox_LilyPond = QtGui.QGroupBox(self.tab_usual_settings)
        self.groupBox_LilyPond.setMinimumSize(QtCore.QSize(211, 81))
        self.groupBox_LilyPond.setObjectName(_fromUtf8("groupBox_LilyPond"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_LilyPond)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.rdo_yesScore = QtGui.QRadioButton(self.groupBox_LilyPond)
        self.rdo_yesScore.setObjectName(_fromUtf8("rdo_yesScore"))
        self.verticalLayout_8.addWidget(self.rdo_yesScore)
        self.rdo_noScore = QtGui.QRadioButton(self.groupBox_LilyPond)
        self.rdo_noScore.setChecked(True)
        self.rdo_noScore.setObjectName(_fromUtf8("rdo_noScore"))
        self.verticalLayout_8.addWidget(self.rdo_noScore)
        self.verticalLayout.addWidget(self.groupBox_LilyPond)
        self.tabs_settings.addTab(self.tab_usual_settings, _fromUtf8(""))
        self.tab_obscure_settings = QtGui.QWidget()
        self.tab_obscure_settings.setObjectName(_fromUtf8("tab_obscure_settings"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_obscure_settings)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_Offsets = QtGui.QGroupBox(self.tab_obscure_settings)
        self.groupBox_Offsets.setObjectName(_fromUtf8("groupBox_Offsets"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_Offsets)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox_Offsets)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.line_intervalOffset = QtGui.QLineEdit(self.groupBox_Offsets)
        self.line_intervalOffset.setText(_fromUtf8("0.5"))
        self.line_intervalOffset.setMaxLength(6)
        self.line_intervalOffset.setObjectName(_fromUtf8("line_intervalOffset"))
        self.horizontalLayout.addWidget(self.line_intervalOffset)
        self.btn_setOffset = QtGui.QPushButton(self.groupBox_Offsets)
        self.btn_setOffset.setObjectName(_fromUtf8("btn_setOffset"))
        self.horizontalLayout.addWidget(self.btn_setOffset)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_Offsets)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.btn_save_settings = QtGui.QPushButton(self.groupBox_8)
        self.btn_save_settings.setObjectName(_fromUtf8("btn_save_settings"))
        self.verticalLayout_15.addWidget(self.btn_save_settings)
        self.btn_load_settings = QtGui.QPushButton(self.groupBox_8)
        self.btn_load_settings.setObjectName(_fromUtf8("btn_load_settings"))
        self.verticalLayout_15.addWidget(self.btn_load_settings)
        self.verticalLayout_9.addWidget(self.groupBox_8)
        self.verticalLayout_2.addWidget(self.groupBox_Offsets)
        self.tabs_settings.addTab(self.tab_obscure_settings, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabs_settings)
        self.tabs_main.addTab(self.tab_settings, _fromUtf8(""))
        self.tab_input = QtGui.QWidget()
        self.tab_input.setObjectName(_fromUtf8("tab_input"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_input)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.widget_4 = QtGui.QWidget(self.tab_input)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btn_chooseFiles = QtGui.QPushButton(self.widget_4)
        self.btn_chooseFiles.setObjectName(_fromUtf8("btn_chooseFiles"))
        self.horizontalLayout_5.addWidget(self.btn_chooseFiles)
        self.btn_chooseDirectories = QtGui.QPushButton(self.widget_4)
        self.btn_chooseDirectories.setObjectName(_fromUtf8("btn_chooseDirectories"))
        self.horizontalLayout_5.addWidget(self.btn_chooseDirectories)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.txt_filenames = QtGui.QPlainTextEdit(self.tab_input)
        self.txt_filenames.setDocumentTitle(_fromUtf8(""))
        self.txt_filenames.setUndoRedoEnabled(False)
        self.txt_filenames.setPlainText(_fromUtf8(""))
        self.txt_filenames.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.txt_filenames.setObjectName(_fromUtf8("txt_filenames"))
        self.verticalLayout_4.addWidget(self.txt_filenames)
        self.btn_analyze = QtGui.QPushButton(self.tab_input)
        self.btn_analyze.setObjectName(_fromUtf8("btn_analyze"))
        self.verticalLayout_4.addWidget(self.btn_analyze)
        self.tabs_main.addTab(self.tab_input, _fromUtf8(""))
        self.tab_output = QtGui.QWidget()
        self.tab_output.setObjectName(_fromUtf8("tab_output"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab_output)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.tabs_output_options = QtGui.QTabWidget(self.tab_output)
        self.tabs_output_options.setObjectName(_fromUtf8("tabs_output_options"))
        self.tab_intervals = QtGui.QWidget()
        self.tab_intervals.setObjectName(_fromUtf8("tab_intervals"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_intervals)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.tab_intervals)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.rdo_ascending_intervals = QtGui.QRadioButton(self.groupBox)
        self.rdo_ascending_intervals.setObjectName(_fromUtf8("rdo_ascending_intervals"))
        self.verticalLayout_13.addWidget(self.rdo_ascending_intervals)
        self.rdo_descending_intervals = QtGui.QRadioButton(self.groupBox)
        self.rdo_descending_intervals.setChecked(True)
        self.rdo_descending_intervals.setObjectName(_fromUtf8("rdo_descending_intervals"))
        self.verticalLayout_13.addWidget(self.rdo_descending_intervals)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_intervals)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.rdo_intervals_by_interval = QtGui.QRadioButton(self.groupBox_2)
        self.rdo_intervals_by_interval.setObjectName(_fromUtf8("rdo_intervals_by_interval"))
        self.verticalLayout_14.addWidget(self.rdo_intervals_by_interval)
        self.rdo_intervals_by_frequency = QtGui.QRadioButton(self.groupBox_2)
        self.rdo_intervals_by_frequency.setChecked(True)
        self.rdo_intervals_by_frequency.setObjectName(_fromUtf8("rdo_intervals_by_frequency"))
        self.verticalLayout_14.addWidget(self.rdo_intervals_by_frequency)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_intervals)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.chk_graph_intervals = QtGui.QCheckBox(self.groupBox_3)
        self.chk_graph_intervals.setObjectName(_fromUtf8("chk_graph_intervals"))
        self.verticalLayout_11.addWidget(self.chk_graph_intervals)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.widget = QtGui.QWidget(self.tab_intervals)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.btn_show_intervals = QtGui.QPushButton(self.widget)
        self.btn_show_intervals.setObjectName(_fromUtf8("btn_show_intervals"))
        self.verticalLayout_12.addWidget(self.btn_show_intervals)
        self.btn_save_intervals = QtGui.QPushButton(self.widget)
        self.btn_save_intervals.setObjectName(_fromUtf8("btn_save_intervals"))
        self.verticalLayout_12.addWidget(self.btn_save_intervals)
        self.gridLayout_2.addWidget(self.widget, 1, 1, 1, 1)
        self.tabs_output_options.addTab(self.tab_intervals, _fromUtf8(""))
        self.tab_triangles = QtGui.QWidget()
        self.tab_triangles.setObjectName(_fromUtf8("tab_triangles"))
        self.gridLayout = QtGui.QGridLayout(self.tab_triangles)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_triangles)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.rdo_ascending_triangles = QtGui.QRadioButton(self.groupBox_4)
        self.rdo_ascending_triangles.setObjectName(_fromUtf8("rdo_ascending_triangles"))
        self.verticalLayout_20.addWidget(self.rdo_ascending_triangles)
        self.rdo_descending_triangles = QtGui.QRadioButton(self.groupBox_4)
        self.rdo_descending_triangles.setChecked(True)
        self.rdo_descending_triangles.setObjectName(_fromUtf8("rdo_descending_triangles"))
        self.verticalLayout_20.addWidget(self.rdo_descending_triangles)
        self.gridLayout.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_triangles)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.rdo_ngrams_by_ngram = QtGui.QRadioButton(self.groupBox_5)
        self.rdo_ngrams_by_ngram.setObjectName(_fromUtf8("rdo_ngrams_by_ngram"))
        self.verticalLayout_21.addWidget(self.rdo_ngrams_by_ngram)
        self.rdo_ngrams_by_freq = QtGui.QRadioButton(self.groupBox_5)
        self.rdo_ngrams_by_freq.setChecked(True)
        self.rdo_ngrams_by_freq.setObjectName(_fromUtf8("rdo_ngrams_by_freq"))
        self.verticalLayout_21.addWidget(self.rdo_ngrams_by_freq)
        self.gridLayout.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_triangles)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.chk_graph_triangles = QtGui.QCheckBox(self.groupBox_6)
        self.chk_graph_triangles.setObjectName(_fromUtf8("chk_graph_triangles"))
        self.verticalLayout_22.addWidget(self.chk_graph_triangles)
        self.gridLayout.addWidget(self.groupBox_6, 0, 1, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_triangles)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_24 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.widget_3 = QtGui.QWidget(self.groupBox_7)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.widget_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.line_show_triangles_n = QtGui.QLineEdit(self.widget_3)
        self.line_show_triangles_n.setMaxLength(20)
        self.line_show_triangles_n.setObjectName(_fromUtf8("line_show_triangles_n"))
        self.horizontalLayout_4.addWidget(self.line_show_triangles_n)
        self.verticalLayout_24.addWidget(self.widget_3)
        self.btn_auto_n = QtGui.QPushButton(self.groupBox_7)
        self.btn_auto_n.setObjectName(_fromUtf8("btn_auto_n"))
        self.verticalLayout_24.addWidget(self.btn_auto_n)
        self.gridLayout.addWidget(self.groupBox_7, 1, 1, 1, 1)
        self.widget_2 = QtGui.QWidget(self.tab_triangles)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btn_show_triangles = QtGui.QPushButton(self.widget_2)
        self.btn_show_triangles.setObjectName(_fromUtf8("btn_show_triangles"))
        self.horizontalLayout_3.addWidget(self.btn_show_triangles)
        self.btn_save_triangles = QtGui.QPushButton(self.widget_2)
        self.btn_save_triangles.setObjectName(_fromUtf8("btn_save_triangles"))
        self.horizontalLayout_3.addWidget(self.btn_save_triangles)
        self.gridLayout.addWidget(self.widget_2, 2, 0, 1, 2)
        self.tabs_output_options.addTab(self.tab_triangles, _fromUtf8(""))
        self.tab_score = QtGui.QWidget()
        self.tab_score.setObjectName(_fromUtf8("tab_score"))
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.tab_score)
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.label_5 = QtGui.QLabel(self.tab_score)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_23.addWidget(self.label_5)
        self.score_slider = QtGui.QSlider(self.tab_score)
        self.score_slider.setMaximum(100)
        self.score_slider.setOrientation(QtCore.Qt.Horizontal)
        self.score_slider.setInvertedAppearance(False)
        self.score_slider.setTickPosition(QtGui.QSlider.NoTicks)
        self.score_slider.setObjectName(_fromUtf8("score_slider"))
        self.verticalLayout_23.addWidget(self.score_slider)
        self.score_progress = QtGui.QProgressBar(self.tab_score)
        self.score_progress.setProperty("value", 0)
        self.score_progress.setObjectName(_fromUtf8("score_progress"))
        self.verticalLayout_23.addWidget(self.score_progress)
        self.tabs_output_options.addTab(self.tab_score, _fromUtf8(""))
        self.tab_targeted_lily = QtGui.QWidget()
        self.tab_targeted_lily.setObjectName(_fromUtf8("tab_targeted_lily"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.tab_targeted_lily)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.label_3 = QtGui.QLabel(self.tab_targeted_lily)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_17.addWidget(self.label_3)
        self.widget_5 = QtGui.QWidget(self.tab_targeted_lily)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(self.widget_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.line_targeted_add_black = QtGui.QLineEdit(self.widget_5)
        self.line_targeted_add_black.setObjectName(_fromUtf8("line_targeted_add_black"))
        self.horizontalLayout_6.addWidget(self.line_targeted_add_black)
        self.btn_targeted_add_black = QtGui.QPushButton(self.widget_5)
        self.btn_targeted_add_black.setObjectName(_fromUtf8("btn_targeted_add_black"))
        self.horizontalLayout_6.addWidget(self.btn_targeted_add_black)
        self.verticalLayout_17.addWidget(self.widget_5)
        self.widget_6 = QtGui.QWidget(self.tab_targeted_lily)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_7 = QtGui.QLabel(self.widget_6)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_7.addWidget(self.label_7)
        self.line_targeted_add_colour = QtGui.QLineEdit(self.widget_6)
        self.line_targeted_add_colour.setObjectName(_fromUtf8("line_targeted_add_colour"))
        self.horizontalLayout_7.addWidget(self.line_targeted_add_colour)
        self.btn_targeted_add_colour = QtGui.QPushButton(self.widget_6)
        self.btn_targeted_add_colour.setObjectName(_fromUtf8("btn_targeted_add_colour"))
        self.horizontalLayout_7.addWidget(self.btn_targeted_add_colour)
        self.verticalLayout_17.addWidget(self.widget_6)
        self.widget_7 = QtGui.QWidget(self.tab_targeted_lily)
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget_7)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.btn_targeted_colour_choose = QtGui.QPushButton(self.widget_7)
        self.btn_targeted_colour_choose.setObjectName(_fromUtf8("btn_targeted_colour_choose"))
        self.horizontalLayout_8.addWidget(self.btn_targeted_colour_choose)
        self.btn_targeted_colour_clear = QtGui.QPushButton(self.widget_7)
        self.btn_targeted_colour_clear.setObjectName(_fromUtf8("btn_targeted_colour_clear"))
        self.horizontalLayout_8.addWidget(self.btn_targeted_colour_clear)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout_17.addWidget(self.widget_7)
        self.widget_8 = QtGui.QWidget(self.tab_targeted_lily)
        self.widget_8.setObjectName(_fromUtf8("widget_8"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget_8)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem1 = QtGui.QSpacerItem(194, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.btn_targeted_choose_score = QtGui.QPushButton(self.widget_8)
        self.btn_targeted_choose_score.setObjectName(_fromUtf8("btn_targeted_choose_score"))
        self.horizontalLayout_9.addWidget(self.btn_targeted_choose_score)
        self.btn_targeted_produce = QtGui.QPushButton(self.widget_8)
        self.btn_targeted_produce.setObjectName(_fromUtf8("btn_targeted_produce"))
        self.horizontalLayout_9.addWidget(self.btn_targeted_produce)
        self.verticalLayout_17.addWidget(self.widget_8)
        self.tabs_output_options.addTab(self.tab_targeted_lily, _fromUtf8(""))
        self.tab_lilypond_summary = QtGui.QWidget()
        self.tab_lilypond_summary.setObjectName(_fromUtf8("tab_lilypond_summary"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_lilypond_summary)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_10 = QtGui.QGroupBox(self.tab_lilypond_summary)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout_25 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.label_8 = QtGui.QLabel(self.groupBox_10)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_25.addWidget(self.label_8)
        self.line_summary_topX = QtGui.QLineEdit(self.groupBox_10)
        self.line_summary_topX.setObjectName(_fromUtf8("line_summary_topX"))
        self.verticalLayout_25.addWidget(self.line_summary_topX)
        self.lbl_summary_triangles_or_ngrams = QtGui.QLabel(self.groupBox_10)
        self.lbl_summary_triangles_or_ngrams.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_summary_triangles_or_ngrams.setObjectName(_fromUtf8("lbl_summary_triangles_or_ngrams"))
        self.verticalLayout_25.addWidget(self.lbl_summary_triangles_or_ngrams)
        self.gridLayout_3.addWidget(self.groupBox_10, 1, 0, 1, 1)
        self.groupBox_13 = QtGui.QGroupBox(self.tab_lilypond_summary)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.rdo_summary_triangles = QtGui.QRadioButton(self.groupBox_13)
        self.rdo_summary_triangles.setChecked(True)
        self.rdo_summary_triangles.setObjectName(_fromUtf8("rdo_summary_triangles"))
        self.horizontalLayout_10.addWidget(self.rdo_summary_triangles)
        self.rdo_summary_intervals = QtGui.QRadioButton(self.groupBox_13)
        self.rdo_summary_intervals.setObjectName(_fromUtf8("rdo_summary_intervals"))
        self.horizontalLayout_10.addWidget(self.rdo_summary_intervals)
        self.gridLayout_3.addWidget(self.groupBox_13, 0, 0, 1, 1)
        self.box_summary_cardinalities = QtGui.QGroupBox(self.tab_lilypond_summary)
        self.box_summary_cardinalities.setObjectName(_fromUtf8("box_summary_cardinalities"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.box_summary_cardinalities)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_11 = QtGui.QLabel(self.box_summary_cardinalities)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_13.addWidget(self.label_11)
        self.line_summary_n = QtGui.QLineEdit(self.box_summary_cardinalities)
        self.line_summary_n.setObjectName(_fromUtf8("line_summary_n"))
        self.horizontalLayout_13.addWidget(self.line_summary_n)
        self.btn_summary_auto_n = QtGui.QPushButton(self.box_summary_cardinalities)
        self.btn_summary_auto_n.setObjectName(_fromUtf8("btn_summary_auto_n"))
        self.horizontalLayout_13.addWidget(self.btn_summary_auto_n)
        self.gridLayout_3.addWidget(self.box_summary_cardinalities, 0, 1, 1, 1)
        self.groupBox_11 = QtGui.QGroupBox(self.tab_lilypond_summary)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_9 = QtGui.QLabel(self.groupBox_11)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_18.addWidget(self.label_9)
        self.line_summary_threshold = QtGui.QLineEdit(self.groupBox_11)
        self.line_summary_threshold.setObjectName(_fromUtf8("line_summary_threshold"))
        self.verticalLayout_18.addWidget(self.line_summary_threshold)
        self.label_10 = QtGui.QLabel(self.groupBox_11)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_18.addWidget(self.label_10)
        self.gridLayout_3.addWidget(self.groupBox_11, 1, 1, 1, 1)
        self.btn_summary_show = QtGui.QPushButton(self.tab_lilypond_summary)
        self.btn_summary_show.setObjectName(_fromUtf8("btn_summary_show"))
        self.gridLayout_3.addWidget(self.btn_summary_show, 2, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 2, 0, 1, 1)
        self.tabs_output_options.addTab(self.tab_lilypond_summary, _fromUtf8(""))
        self.verticalLayout_10.addWidget(self.tabs_output_options)
        self.txt_results = QtGui.QPlainTextEdit(self.tab_output)
        self.txt_results.setPlainText(_fromUtf8(""))
        self.txt_results.setBackgroundVisible(False)
        self.txt_results.setObjectName(_fromUtf8("txt_results"))
        self.verticalLayout_10.addWidget(self.txt_results)
        self.tabs_main.addTab(self.tab_output, _fromUtf8(""))
        self.verticalLayout_19.addWidget(self.tabs_main)
        MainWindow.setCentralWidget(self.centralWidget)
        self.label_2.setBuddy(self.line_n)
        self.label.setBuddy(self.line_intervalOffset)
        self.label_4.setBuddy(self.line_show_triangles_n)
        self.label_6.setBuddy(self.line_targeted_add_black)
        self.label_11.setBuddy(self.line_summary_n)

        self.retranslateUi(MainWindow)
        self.tabs_main.setCurrentIndex(1)
        self.tabs_settings.setCurrentIndex(0)
        self.tabs_output_options.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.groupBox_heedQuality.setTitle(QtGui.QApplication.translate("MainWindow", "Interval Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_heedQuality.setText(QtGui.QApplication.translate("MainWindow", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_ignoreQuality.setText(QtGui.QApplication.translate("MainWindow", "Ignore", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Octaves.setTitle(QtGui.QApplication.translate("MainWindow", "Octaves", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_compoundIntervals.setText(QtGui.QApplication.translate("MainWindow", "Compound Intervals", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_simpleIntervals.setText(QtGui.QApplication.translate("MainWindow", "Simple Intervals", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("MainWindow", "How to Choose Voices to Analyze", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_choose_every_file.setText(QtGui.QApplication.translate("MainWindow", "Choose once for all files", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_choose_just_once.setText(QtGui.QApplication.translate("MainWindow", "Choose for every file", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxwhichNs.setTitle(QtGui.QApplication.translate("MainWindow", "Which Values of n?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "n = ", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_setN.setText(QtGui.QApplication.translate("MainWindow", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_LilyPond.setTitle(QtGui.QApplication.translate("MainWindow", "LilyPond", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_yesScore.setText(QtGui.QApplication.translate("MainWindow", "Produce Score", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_noScore.setText(QtGui.QApplication.translate("MainWindow", "Do not Produce Score", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_settings.setTabText(self.tabs_settings.indexOf(self.tab_usual_settings), QtGui.QApplication.translate("MainWindow", "Usual Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Offsets.setTitle(QtGui.QApplication.translate("MainWindow", "Offsets", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Offset between Intervals:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_setOffset.setText(QtGui.QApplication.translate("MainWindow", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("MainWindow", "Load and Save Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save_settings.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_load_settings.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_settings.setTabText(self.tabs_settings.indexOf(self.tab_obscure_settings), QtGui.QApplication.translate("MainWindow", "Obscure Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_main.setTabText(self.tabs_main.indexOf(self.tab_settings), QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_chooseFiles.setText(QtGui.QApplication.translate("MainWindow", "Choose Files", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_chooseDirectories.setText(QtGui.QApplication.translate("MainWindow", "Choose Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_analyze.setText(QtGui.QApplication.translate("MainWindow", "Analyze!", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_main.setTabText(self.tabs_main.indexOf(self.tab_input), QtGui.QApplication.translate("MainWindow", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Sort Order", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_ascending_intervals.setText(QtGui.QApplication.translate("MainWindow", "Low to High (Ascending)", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_descending_intervals.setText(QtGui.QApplication.translate("MainWindow", "High to Low (Descending)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Sort Object", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_intervals_by_interval.setText(QtGui.QApplication.translate("MainWindow", "By Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_intervals_by_frequency.setText(QtGui.QApplication.translate("MainWindow", "By Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_graph_intervals.setToolTip(QtGui.QApplication.translate("MainWindow", "Output results as a chart rather than a list", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_graph_intervals.setText(QtGui.QApplication.translate("MainWindow", "Produce Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_show_intervals.setToolTip(QtGui.QApplication.translate("MainWindow", "Display results below (list), or in a new window (graph)", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_show_intervals.setText(QtGui.QApplication.translate("MainWindow", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save_intervals.setToolTip(QtGui.QApplication.translate("MainWindow", "Save results to a file", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save_intervals.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_output_options.setTabText(self.tabs_output_options.indexOf(self.tab_intervals), QtGui.QApplication.translate("MainWindow", "Intervals", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Sort Order", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_ascending_triangles.setText(QtGui.QApplication.translate("MainWindow", "Low to High (Ascending)", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_descending_triangles.setText(QtGui.QApplication.translate("MainWindow", "High to Low (Descending)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Sort Object", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_ngrams_by_ngram.setText(QtGui.QApplication.translate("MainWindow", "By Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_ngrams_by_freq.setText(QtGui.QApplication.translate("MainWindow", "By Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_graph_triangles.setText(QtGui.QApplication.translate("MainWindow", "Produce Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Cardinalities", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "n = ", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_auto_n.setText(QtGui.QApplication.translate("MainWindow", "Auto Fill", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_show_triangles.setText(QtGui.QApplication.translate("MainWindow", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save_triangles.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_output_options.setTabText(self.tabs_output_options.indexOf(self.tab_triangles), QtGui.QApplication.translate("MainWindow", "Triangles", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "How much money?", None, QtGui.QApplication.UnicodeUTF8))
        self.score_progress.setFormat(QtGui.QApplication.translate("MainWindow", "$%p", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_output_options.setTabText(self.tabs_output_options.indexOf(self.tab_score), QtGui.QApplication.translate("MainWindow", "Score", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Generate a LilyPond score. Annotate only certain triangles, optionally in colour. You must add each triangle once, exactly as the str(NGram) representation appears.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Annotate this triangle in black:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_targeted_add_black.setText(QtGui.QApplication.translate("MainWindow", "Add to List", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Annotate this triangle in colour:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_targeted_add_colour.setText(QtGui.QApplication.translate("MainWindow", "Add to List", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_targeted_colour_choose.setText(QtGui.QApplication.translate("MainWindow", "Choose Colour", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_targeted_colour_clear.setText(QtGui.QApplication.translate("MainWindow", "Clear Colour", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_targeted_choose_score.setText(QtGui.QApplication.translate("MainWindow", "Choose Score", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_targeted_produce.setText(QtGui.QApplication.translate("MainWindow", "Choose Voices then Annotate", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_output_options.setTabText(self.tabs_output_options.indexOf(self.tab_targeted_lily), QtGui.QApplication.translate("MainWindow", "Targeted LilyPond Output", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("MainWindow", "Most Common", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Output the most common ", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_summary_triangles_or_ngrams.setText(QtGui.QApplication.translate("MainWindow", "triangles.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_13.setTitle(QtGui.QApplication.translate("MainWindow", "Print Summary of...", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_summary_triangles.setText(QtGui.QApplication.translate("MainWindow", "Triangles", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_summary_intervals.setText(QtGui.QApplication.translate("MainWindow", "Intervals", None, QtGui.QApplication.UnicodeUTF8))
        self.box_summary_cardinalities.setTitle(QtGui.QApplication.translate("MainWindow", "Cardinalities", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "n = ", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_summary_auto_n.setText(QtGui.QApplication.translate("MainWindow", "Auto Fill", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_11.setTitle(QtGui.QApplication.translate("MainWindow", "Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Do not output if fewer than ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "occurrences.", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_summary_show.setText(QtGui.QApplication.translate("MainWindow", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_output_options.setTabText(self.tabs_output_options.indexOf(self.tab_lilypond_summary), QtGui.QApplication.translate("MainWindow", "LilyPond Statistics Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_main.setTabText(self.tabs_main.indexOf(self.tab_output), QtGui.QApplication.translate("MainWindow", "Show", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

