# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/christo/ELVIS/programs/vis/qt/select_voices.ui'
#
# Created: Sat Aug 18 22:28:14 2012
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_select_voices(object):
    def setupUi(self, select_voices):
        select_voices.setObjectName("select_voices")
        select_voices.setWindowModality(QtCore.Qt.ApplicationModal)
        select_voices.resize(476, 241)
        self.verticalLayout = QtGui.QVBoxLayout(select_voices)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtGui.QWidget(select_voices)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.widget_5 = QtGui.QWidget(self.widget)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout = QtGui.QGridLayout(self.widget_5)
        self.gridLayout.setObjectName("gridLayout")
        self.rdo_all = QtGui.QRadioButton(self.widget_5)
        self.rdo_all.setChecked(True)
        self.rdo_all.setObjectName("rdo_all")
        self.gridLayout.addWidget(self.rdo_all, 0, 0, 1, 1)
        self.rdo_these_parts = QtGui.QRadioButton(self.widget_5)
        self.rdo_these_parts.setObjectName("rdo_these_parts")
        self.gridLayout.addWidget(self.rdo_these_parts, 1, 0, 1, 1)
        self.line_these_parts = QtGui.QLineEdit(self.widget_5)
        self.line_these_parts.setEnabled(False)
        self.line_these_parts.setMinimumSize(QtCore.QSize(148, 0))
        self.line_these_parts.setObjectName("line_these_parts")
        self.gridLayout.addWidget(self.line_these_parts, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.rdo_part_and_bs = QtGui.QRadioButton(self.widget_5)
        self.rdo_part_and_bs.setObjectName("rdo_part_and_bs")
        self.gridLayout.addWidget(self.rdo_part_and_bs, 2, 0, 1, 1)
        self.line_part_and_bs = QtGui.QLineEdit(self.widget_5)
        self.line_part_and_bs.setEnabled(False)
        self.line_part_and_bs.setMinimumSize(QtCore.QSize(148, 0))
        self.line_part_and_bs.setObjectName("line_part_and_bs")
        self.gridLayout.addWidget(self.line_part_and_bs, 2, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 2, 1, 1)
        self.rdo_choose_these = QtGui.QRadioButton(self.widget_5)
        self.rdo_choose_these.setObjectName("rdo_choose_these")
        self.gridLayout.addWidget(self.rdo_choose_these, 3, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 3, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.widget_7 = QtGui.QWidget(self.widget)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.widget_8 = QtGui.QWidget(self.widget_7)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.chk_voice_0 = QtGui.QCheckBox(self.widget_8)
        self.chk_voice_0.setObjectName("chk_voice_0")
        self.verticalLayout_3.addWidget(self.chk_voice_0)
        self.horizontalLayout_5.addWidget(self.widget_8)
        self.verticalLayout_2.addWidget(self.widget_7)
        self.verticalLayout.addWidget(self.widget)
        self.line = QtGui.QFrame(select_voices)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.widget_2 = QtGui.QWidget(select_voices)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.btn_continue = QtGui.QPushButton(self.widget_2)
        self.btn_continue.setObjectName("btn_continue")
        self.horizontalLayout.addWidget(self.btn_continue)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(select_voices)
        QtCore.QMetaObject.connectSlotsByName(select_voices)

    def retranslateUi(self, select_voices):
        select_voices.setWindowTitle(QtGui.QApplication.translate("select_voices", "vis Voices Selector", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("select_voices", "Choose which voices to analyze.", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_all.setText(QtGui.QApplication.translate("select_voices", "Compare all part combinations.", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_these_parts.setText(QtGui.QApplication.translate("select_voices", "Compare these parts:", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_part_and_bs.setText(QtGui.QApplication.translate("select_voices", "Compare this part with basso seguente:", None, QtGui.QApplication.UnicodeUTF8))
        self.rdo_choose_these.setText(QtGui.QApplication.translate("select_voices", "Choose two specific voices:", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_voice_0.setText(QtGui.QApplication.translate("select_voices", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_continue.setText(QtGui.QApplication.translate("select_voices", "Continue", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    select_voices = QtGui.QDialog()
    ui = Ui_select_voices()
    ui.setupUi(select_voices)
    select_voices.show()
    sys.exit(app.exec_())

